
const C=window.JF_CONFIG;
const sb=window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey,{
  auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}
});
const $=id=>document.getElementById(id);
const state={session:null,user:null,profile:null,view:'dashboard',tasks:[],events:[],meetings:[],projects:[],contacts:[],institutions:[],notes:[],participation_records:[],opportunities:[],notifications:[],month:new Date(),google:null};
const priorityRank={Urgente:1,Alta:2,Media:3,Baja:4};

const schemas={
 tasks:{title:'Tarea',eyebrow:'CHECKLIST JUVENTUD',fields:[
  ['title','Título','text',true,'full'],['description','Descripción','textarea',false,'full'],
  ['category','Categoría','select',false,'',['Seguimiento','Reunión','Evento','Taller','Actividad','Nota','Solicitud','Locomoción','Llamada','WhatsApp','Email','Convenio','Difusión','Redes sociales','Capacitación','Proyecto','Compra','Presupuesto','Coordinación institucional','Otro']],
  ['status','Estado','select',false,'',['Pendiente','En proceso','Esperando respuesta','Agendada','Confirmada','Realizada','Cancelada','Postergada']],
  ['priority','Prioridad','select',false,'',['Media','Urgente','Alta','Baja']],['task_date','Fecha','date'],['task_time','Hora','time'],['deadline','Fecha límite','date'],
  ['institution_name','Institución','text'],['contact_name','Contacto','text'],['project_name','Proyecto','text'],['reminder','Recordatorio','select',false,'',['','Mismo día','1 día antes','2 días antes','3 días antes','7 días antes','2 horas antes']],
  ['notes','Observaciones','textarea',false,'full'],['recurrence_type','Repetir','select',false,'',['','Diaria','Semanal','Mensual','Anual']],['recurrence_interval','Cada cuántas unidades','number'],['recurrence_end_date','Repetir hasta','date'],['google_sync','Sincronizar con Google Calendar','checkbox',false,'full']
 ]},
 events:{title:'Evento',eyebrow:'EVENTOS Y ACTIVIDADES',fields:[
  ['name','Nombre','text',true,'full'],['event_date','Fecha','date',true],['start_time','Hora inicio','time'],['end_time','Hora final','time'],['place','Lugar','text'],['address','Dirección','text'],
  ['organizer','Organiza','text'],['collaborators','Instituciones colaboradoras','text'],['target_audience','Público objetivo','text'],['expected_participants','Participantes estimados','number'],
  ['actual_participants','Participantes reales','number'],['description','Descripción','textarea',false,'full'],['objectives','Objetivos','textarea',false,'full'],['responsible_name','Responsable','text'],['budget','Presupuesto','number'],['logistics','Logística / necesidades','textarea',false,'full'],['evaluation','Evaluación','textarea',false,'full']
 ]},
 meetings:{title:'Reunión',eyebrow:'COORDINACIÓN',fields:[
  ['subject','Tema','text',true,'full'],['meeting_date','Fecha','date',true],['meeting_time','Hora','time'],['place','Lugar','text'],['institutions','Instituciones','text',false,'full'],['participants','Participantes','textarea',false,'full'],['agenda','Orden del día','textarea',false,'full'],['discussed','Temas tratados','textarea',false,'full'],['decisions','Decisiones','textarea',false,'full'],['commitments','Compromisos','textarea',false,'full'],['next_steps','Próximos pasos','textarea',false,'full']
 ]},
 projects:{title:'Proyecto',eyebrow:'PROYECTOS',fields:[
  ['name','Nombre','text',true,'full'],['status','Estado','select',false,'',['Idea','Planificación','En ejecución','Pausado','Finalizado','Cancelado']],['start_date','Inicio','date'],['end_date','Fin','date'],['objective','Objetivo','textarea',false,'full'],['description','Descripción','textarea',false,'full'],['budget','Presupuesto','number'],['results','Resultados','textarea',false,'full']
 ]},
 contacts:{title:'Contacto',eyebrow:'CONTACTOS',fields:[
  ['first_name','Nombre','text',true],['last_name','Apellido','text'],['organization','Institución / organización','text',false,'full'],['position','Cargo','text'],['phone','Teléfono','text'],['whatsapp','WhatsApp','text'],['email','Email','email'],['area','Área','text'],['category','Categoría','text'],['notes','Observaciones','textarea',false,'full']
 ]},
 institutions:{title:'Institución',eyebrow:'INSTITUCIONES',fields:[
  ['name','Nombre','text',true,'full'],['area','Área','text'],['locality','Localidad','text'],['address','Dirección','text',false,'full'],['phone','Teléfono','text'],['email','Email','email'],['website','Web','text'],['notes','Observaciones','textarea',false,'full']
 ]},
 notes:{title:'Nota / solicitud',eyebrow:'GESTIONES',fields:[
  ['note_date','Fecha','date',true],['number','Número','text'],['recipient','Destinatario','text'],['department','Dirección / área','text'],['subject','Asunto','text',true,'full'],['reason','Motivo','textarea',false,'full'],['responsible_name','Responsable','text'],['status','Estado','select',false,'',['Borrador','Pendiente de firma','Firmada','Presentada','Enviada','Esperando respuesta','Aprobada','Rechazada','Finalizada']],['followup_date','Seguimiento','date'],['response','Respuesta / resultado','textarea',false,'full']
 ]},
 participation_records:{title:'Participación',eyebrow:'ALCANCE',fields:[
  ['activity_name','Actividad','text',true,'full'],['activity_date','Fecha','date',true],['total','Total','number'],['under_14','Menores de 14','number'],['age_14_17','14–17','number'],['age_18_24','18–24','number'],['age_25_29','25–29','number'],['over_29','30 o más','number'],['rural','Medio rural','number'],['locality','Localidad','text'],['educational_institution','Institución educativa','text'],['notes','Observaciones','textarea',false,'full']
 ]},
 opportunities:{title:'Oportunidad',eyebrow:'PORTAL JOVEN',fields:[
  ['title','Título','text',true,'full'],['category','Categoría','select',true,'',['Becas','Trabajo','Cursos','Estudios','Cultura','Deportes','Salud','Emprendimientos','Participación','Otros']],['organization','Organización','text'],['status','Estado','select',false,'',['Abierta','Próxima','Cerrada']],['summary','Resumen','textarea',false,'full'],['description','Descripción','textarea',false,'full'],['age_min','Edad mínima','number'],['age_max','Edad máxima','number'],['locality','Localidad / alcance','text'],['modality','Modalidad','text'],['deadline','Fecha límite','date'],['external_url','Enlace externo','url',false,'full'],['contact_email','Email','email'],['contact_phone','Teléfono','text'],['public_enabled','Publicar','checkbox'],['featured','Destacada','checkbox']
 ]}
};

function esc(v=''){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]))}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2500)}
function fmtDate(v){if(!v)return 'Sin fecha';return new Intl.DateTimeFormat('es-UY',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v+'T12:00:00'))}
function fullDate(){let s=new Intl.DateTimeFormat('es-UY',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:C.timezone}).format(new Date());return s.charAt(0).toUpperCase()+s.slice(1)}
function isoToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:C.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function canWrite(){return ['admin','equipo'].includes(state.profile?.role)&&state.profile?.active}
function isAdmin(){return state.profile?.role==='admin'&&state.profile?.active}
function publicRoute(){return (location.hash||'#/login').replace(/^#/,'')}
function rowTitle(resource,x){return resource==='tasks'?x.title:resource==='events'?x.name:resource==='meetings'?x.subject:resource==='projects'?x.name:resource==='contacts'?`${x.first_name} ${x.last_name||''}`:resource==='institutions'?x.name:resource==='notes'?x.subject:resource==='participation_records'?x.activity_name:resource==='opportunities'?x.title:'Registro'}
function entityDate(resource,x){return resource==='tasks'?(x.deadline||x.task_date):resource==='events'?x.event_date:resource==='meetings'?x.meeting_date:resource==='notes'?x.note_date:resource==='participation_records'?x.activity_date:resource==='opportunities'?x.deadline:''}

async function init(){
 $('todayLabel').textContent=fullDate();
 if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
 const {data:{session}}=await sb.auth.getSession();state.session=session;state.user=session?.user||null;
 sb.auth.onAuthStateChange(async(_event,session)=>{state.session=session;state.user=session?.user||null;await route()});
 window.addEventListener('hashchange',route);
 bindStatic();
 await route();
}

function bindStatic(){
 document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));$('loginForm').classList.toggle('hidden',b.dataset.authTab!=='login');$('signupForm').classList.toggle('hidden',b.dataset.authTab!=='signup')});
 $('loginForm').onsubmit=login;$('signupForm').onsubmit=signup;$('logoutBtn').onclick=logout;$('pendingLogout').onclick=logout;$('bootstrapAdminBtn').onclick=bootstrapAdmin;
 $('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
 document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openEntity(b.dataset.add));
 $('quickAddBtn').onclick=()=>openEntity('tasks');$('closeModal').onclick=closeModal;$('backdrop').onclick=closeModal;$('entityForm').onsubmit=saveEntity;
 $('closeDetail').onclick=closeDetail;$('detailBackdrop').onclick=closeDetail;
 $('taskStatusFilter').onchange=renderTasks;$('taskPriorityFilter').onchange=renderTasks;$('globalSearch').oninput=()=>{if(state.view==='tasks')renderTasks()};
 $('prevMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$('nextMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};
 $('notifBtn').onclick=()=>{$('notificationDrawer').classList.add('show');renderNotifications()};$('closeDrawer').onclick=()=>$('notificationDrawer').classList.remove('show');$('readAllBtn').onclick=readAllNotifications;
 $('startScanner').onclick=startScanner;$('stopScanner').onclick=stopScanner;$('manualCheckin').onclick=()=>doCheckin($('manualToken').value);
 $('exportPdfBtn').onclick=exportPdf;$('exportExcelBtn').onclick=exportExcel;$('saveMemory').onclick=saveMemory;$('memoryPdf').onclick=memoryPdf;$('memoryYear').onchange=loadMemory;
 $('googleConnectBtn').onclick=connectGoogle;$('googleTestEmail').onclick=testEmail;
}

async function route(){
 $('loading').classList.add('hidden');$('authScreen').classList.add('hidden');$('pendingScreen').classList.add('hidden');$('app').classList.add('hidden');$('publicScreen').classList.add('hidden');
 const r=publicRoute();
 if(r.startsWith('/agenda')||r.startsWith('/oportunidades')||r.startsWith('/inscripcion/')||r.startsWith('/mi-inscripcion/')) return renderPublic(r);
 if(!state.session){$('authScreen').classList.remove('hidden');if(r!='/login')history.replaceState(null,'','#/login');return}
 await loadProfile();
 if(!state.profile?.active){$('pendingScreen').classList.remove('hidden');return}
 $('app').classList.remove('hidden');$('currentUserName').textContent=state.profile.full_name||state.user.email;$('currentUserRole').textContent={admin:'Administrador',equipo:'Equipo Juventud',consulta:'Consulta'}[state.profile.role]||state.profile.role;
 await loadAll();
 const wanted=r.startsWith('/')?r.slice(1).split('?')[0]:'dashboard';setView(document.getElementById('view-'+wanted)?wanted:'dashboard',false);
}

async function login(e){e.preventDefault();$('authMessage').textContent='';const {error}=await sb.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});if(error)$('authMessage').textContent=error.message}
async function signup(e){e.preventDefault();$('authMessage').textContent='';const {data,error}=await sb.auth.signUp({email:$('signupEmail').value,password:$('signupPassword').value,options:{data:{full_name:$('signupName').value.trim()}}});if(error)return $('authMessage').textContent=error.message;$('authMessage').textContent=data.session?'Usuario creado.':'Usuario creado. Revisá tu correo si Supabase solicita confirmar la cuenta.'}
async function logout(){await sb.auth.signOut();state.session=null;state.user=null;state.profile=null;location.hash='#/login'}
async function loadProfile(){const {data,error}=await sb.from('profiles').select('*').eq('id',state.user.id).maybeSingle();if(error){toast(error.message);return}state.profile=data}
async function bootstrapAdmin(){const code=$('setupCode').value.trim();if(!code)return toast('Ingresá el código de instalación');const {data,error}=await sb.rpc('bootstrap_first_admin',{p_setup_code:code});if(error)return toast(error.message);if(data){toast('Primer Administrador activado');await route()}else toast('Ya existe un Administrador. Tu usuario debe ser habilitado por él.')}

async function loadAll(){
 const calls=[
  ['tasks',sb.from('tasks').select('*').eq('archived',false).order('updated_at',{ascending:false})],
  ['events',sb.from('events').select('*').eq('archived',false).order('event_date')],
  ['meetings',sb.from('meetings').select('*').eq('archived',false).order('meeting_date',{ascending:false})],
  ['projects',sb.from('projects').select('*').eq('archived',false).order('updated_at',{ascending:false})],
  ['contacts',sb.from('contacts').select('*').eq('archived',false).order('first_name')],
  ['institutions',sb.from('institutions').select('*').eq('archived',false).order('name')],
  ['notes',sb.from('notes').select('*').eq('archived',false).order('note_date',{ascending:false})],
  ['participation_records',sb.from('participation_records').select('*').order('activity_date',{ascending:false})],
  ['opportunities',sb.from('opportunities').select('*').eq('archived',false).order('featured',{ascending:false})],
  ['notifications',sb.from('notifications').select('*').eq('user_id',state.user.id).order('created_at',{ascending:false}).limit(100)]
 ];
 await Promise.all(calls.map(async([key,p])=>{const {data,error}=await p;if(error)console.warn(key,error);else state[key]=data||[]}));
 renderAll();await googleStatus();if(isAdmin())await renderUsers();
}

function setView(v,updateHash=true){state.view=v;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('view-'+v)?.classList.add('active');document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('sidebar').classList.remove('open');if(updateHash)history.replaceState(null,'','#/'+v);if(v==='reports')loadMemory();if(v==='settings'&&isAdmin())renderUsers();if(v==='checkin')prepareScanner()}
function renderAll(){renderDashboard();renderTasks();renderCalendar();renderCards();renderNotifications()}
function renderDashboard(){
 const today=isoToday(),active=state.tasks.filter(t=>!['Realizada','Cancelada'].includes(t.status)),ref=t=>t.deadline||t.task_date||'';
 const overdue=active.filter(t=>ref(t)&&ref(t)<today).length,waiting=active.filter(t=>t.status==='Esperando respuesta').length,done=state.tasks.filter(t=>t.status==='Realizada').length,todayTasks=active.filter(t=>t.task_date===today||t.deadline===today);
 const stats=[['Para hoy',todayTasks.length],['Pendientes',active.length],['Esperando respuesta',waiting],['Eventos',state.events.filter(e=>e.event_date>=today).length],['Atrasadas',overdue,'alert'],['Completadas',done]];
 $('dashboardStats').innerHTML=stats.map(([l,n,c=''])=>`<div class="stat ${c}"><span>${l}</span><strong>${n}</strong></div>`).join('');
 $('todayItems').innerHTML=todayTasks.length?todayTasks.slice(0,8).map(taskMini).join(''):'<div class="empty">Sin tareas para hoy.</div>';
 $('priorityItems').innerHTML=active.sort((a,b)=>(priorityRank[a.priority]||9)-(priorityRank[b.priority]||9)).slice(0,6).map(taskMini).join('')||'<div class="empty">Sin pendientes.</div>';
 $('upcomingItems').innerHTML=state.events.filter(e=>e.event_date>=today).slice(0,8).map(e=>`<div class="mini-row"><div><h4>${esc(e.name)}</h4><div class="meta">${fmtDate(e.event_date)} · ${esc(e.start_time||'Sin hora')} · ${esc(e.place||'Lugar a confirmar')}</div></div></div>`).join('')||'<div class="empty">Sin eventos próximos.</div>';
}
function taskMini(t){return `<div class="mini-row"><div><h4>${esc(t.title)}</h4><div class="meta">${fmtDate(t.deadline||t.task_date)} · ${esc(t.status)}</div><span class="badge ${esc(t.priority)}">${esc(t.priority)}</span></div></div>`}

function renderTasks(){
 let list=[...state.tasks],s=$('taskStatusFilter').value,p=$('taskPriorityFilter').value,q=$('globalSearch').value.trim().toLowerCase();if(s)list=list.filter(x=>x.status===s);if(p)list=list.filter(x=>x.priority===p);if(q)list=list.filter(x=>[x.title,x.description,x.institution_name,x.project_name,x.contact_name].join(' ').toLowerCase().includes(q));
 list.sort((a,b)=>{if(a.status==='Realizada'&&b.status!=='Realizada')return 1;if(b.status==='Realizada'&&a.status!=='Realizada')return -1;return(priorityRank[a.priority]||9)-(priorityRank[b.priority]||9)});
 $('tasksList').innerHTML=list.length?list.map(t=>`<div class="row"><div><h3>${esc(t.title)}</h3><div class="meta">${esc(t.category)} · ${esc(t.status)} · ${fmtDate(t.deadline||t.task_date)} ${t.google_event_id?'· 📅':''} ${t.recurrence_type?'· ↻ '+esc(t.recurrence_type):''}</div><span class="badge ${esc(t.priority)}">${esc(t.priority)}</span>${t.institution_name?` <span class="badge">${esc(t.institution_name)}</span>`:''}</div><div class="row-actions"><button onclick="openDetails('tasks','${t.id}')">👁️</button>${canWrite()?`<button onclick="editEntity('tasks','${t.id}')">✏️</button><button onclick="toggleTask('${t.id}')">${t.status==='Realizada'?'↩️':'✅'}</button><button onclick="syncGoogle('tasks','${t.id}')">📅</button><button onclick="archiveEntity('tasks','${t.id}')">🗑️</button>`:''}</div></div>`).join(''):'<div class="empty">No hay tareas para este filtro.</div>';
}
function renderCards(){
 cardList('events',state.events,x=>x.name,x=>`${fmtDate(x.event_date)} · ${x.start_time||'Sin hora'} · ${x.place||'Lugar a confirmar'}`);
 cardList('meetings',state.meetings,x=>x.subject,x=>`${fmtDate(x.meeting_date)} · ${x.meeting_time||'Sin hora'} · ${x.place||'Lugar a confirmar'}`);
 cardList('projects',state.projects,x=>x.name,x=>`${x.status} · ${x.start_date?fmtDate(x.start_date):'Sin fecha'}`);
 cardList('contacts',state.contacts,x=>`${x.first_name} ${x.last_name||''}`,x=>`${x.organization||'Sin institución'} · ${x.phone||x.whatsapp||x.email||'Sin contacto'}`);
 cardList('institutions',state.institutions,x=>x.name,x=>`${x.area||'Sin área'} · ${x.locality||'Flores'}`);
 cardList('notes',state.notes,x=>x.subject,x=>`${fmtDate(x.note_date)} · ${x.status} · ${x.recipient||'Sin destinatario'}`);
 cardList('participation_records',state.participation_records,x=>x.activity_name,x=>`${fmtDate(x.activity_date)} · Total: ${x.total} · ${x.locality||'Sin localidad'}`);
 cardList('opportunities',state.opportunities,x=>x.title,x=>`${x.category} · ${x.status}${x.deadline?' · Cierre '+fmtDate(x.deadline):''}${x.public_enabled?' · 🌐 Pública':''}`);
}
function cardList(resource,list,titleFn,metaFn){const el=$(resource==='participation_records'?'participationList':resource+'List');if(!el)return;el.innerHTML=list.length?list.map(x=>`<article class="card"><p class="eyebrow">${esc(resource.replaceAll('_',' '))}</p><h3>${esc(titleFn(x))}</h3><p class="muted">${esc(metaFn(x))}</p><div class="actions"><button class="secondary-btn" onclick="openDetails('${resource}','${x.id}')">Ver detalle</button>${canWrite()?`<button class="secondary-btn" onclick="editEntity('${resource}','${x.id}')">Editar</button><button class="danger-btn" onclick="archiveEntity('${resource}','${x.id}')">Archivar</button>${resource==='events'?`<button class="secondary-btn" onclick="openChecklist('${x.id}')">☑ Checklist</button><button class="secondary-btn" onclick="openEventPublic('${x.id}')">🌐 Público</button><button class="secondary-btn" onclick="syncGoogle('events','${x.id}')">📅</button>`:''}`:''}</div></article>`).join(''):'<div class="empty">No hay registros.</div>'}

function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth();$('monthTitle').textContent=new Intl.DateTimeFormat('es-UY',{month:'long',year:'numeric'}).format(state.month);const first=new Date(y,m,1),start=(first.getDay()+6)%7;let html=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=>`<div class="cal-head">${x}</div>`).join('');for(let i=0;i<42;i++){const d=new Date(y,m,1-start+i),iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,ts=state.tasks.filter(t=>t.task_date===iso).slice(0,2),es=state.events.filter(e=>e.event_date===iso).slice(0,2);html+=`<div class="cal-day ${d.getMonth()!==m?'other':''}"><div class="cal-num">${d.getDate()}</div>${ts.map(t=>`<div class="cal-item">${esc(t.title)}</div>`).join('')}${es.map(e=>`<div class="cal-item event">${esc(e.name)}</div>`).join('')}</div>`}$('calendarGrid').innerHTML=html}

function openEntity(resource,id=null){if(!canWrite())return toast('Tu rol es solo de consulta');const schema=schemas[resource],record=id?state[resource].find(x=>x.id===id):{};$('modalEyebrow').textContent=schema.eyebrow;$('modalTitle').textContent=(id?'Editar ':'Nuevo/a ')+schema.title.toLowerCase();$('entityForm').dataset.resource=resource;$('entityForm').dataset.id=id||'';$('entityForm').innerHTML=schema.fields.map(([name,label,type='text',required=false,cls='',options=[]])=>{const v=record?.[name]??(type==='checkbox'?false:'');if(type==='textarea')return`<label class="${cls}">${label}<textarea name="${name}" rows="3" ${required?'required':''}>${esc(v)}</textarea></label>`;if(type==='select')return`<label class="${cls}">${label}<select name="${name}" ${required?'required':''}>${options.map(o=>`<option value="${esc(o)}" ${String(v)===String(o)?'selected':''}>${esc(o||'Sin selección')}</option>`).join('')}</select></label>`;if(type==='checkbox')return`<label class="checkbox ${cls}"><input type="checkbox" name="${name}" ${v?'checked':''}> ${label}</label>`;return`<label class="${cls}">${label}<input name="${name}" type="${type}" value="${esc(v)}" ${required?'required':''}></label>`}).join('')+`<div class="form-actions"><button type="button" class="secondary-btn" onclick="closeModal()">Cancelar</button><button class="primary-btn" type="submit">Guardar</button></div>`;$('backdrop').classList.add('show');$('modal').classList.add('show')}
function closeModal(){$('backdrop').classList.remove('show');$('modal').classList.remove('show')}
window.editEntity=openEntity;window.closeModal=closeModal;
async function saveEntity(e){e.preventDefault();const resource=e.target.dataset.resource,id=e.target.dataset.id,schema=schemas[resource],body={};for(const[name,,type]of schema.fields){const el=e.target.elements[name];if(!el)continue;let v=type==='checkbox'?el.checked:el.value;if(type==='number')v=v===''?0:Number(v);if((type==='date'||type==='time')&&v==='')v=null;body[name]=v}body.created_by=state.user.id;let q=id?sb.from(resource).update(body).eq('id',id):sb.from(resource).insert(body);const{error}=await q;if(error)return toast(error.message);closeModal();await loadAll();toast(id?'Registro actualizado':'Registro creado')}
window.archiveEntity=async(resource,id)=>{if(!canWrite()||!confirm('¿Archivar este registro?'))return;let q;if(['participation_records'].includes(resource))q=sb.from(resource).delete().eq('id',id);else q=sb.from(resource).update({archived:true}).eq('id',id);const{error}=await q;if(error)return toast(error.message);await loadAll();toast('Registro archivado')};
window.toggleTask=async id=>{const t=state.tasks.find(x=>x.id===id);if(!t)return;if(t.status==='Realizada'){const{error}=await sb.from('tasks').update({status:'Pendiente',completed_at:null}).eq('id',id);if(error)return toast(error.message)}else{const{error}=await sb.rpc('complete_task',{p_task_id:id,p_result:''});if(error)return toast(error.message)}await loadAll();toast('Tarea actualizada')};

function closeDetail(){$('detailBackdrop').classList.remove('show');$('detailModal').classList.remove('show')}
window.closeDetail=closeDetail;
window.openDetails=async(resource,id)=>{const item=state[resource]?.find(x=>x.id===id);if(!item)return;$('detailEyebrow').textContent=resource.replaceAll('_',' ').toUpperCase();$('detailTitle').textContent=rowTitle(resource,item);const atts=await getAttachments(resource,id);const body=Object.entries(item).filter(([k,v])=>!['id','archived','created_by','created_at','updated_at'].includes(k)&&v!==''&&v!==null&&v!==false&&v!==0).map(([k,v])=>`<div class="mini-row"><div><strong>${esc(k.replaceAll('_',' '))}</strong><div class="meta">${esc(v)}</div></div></div>`).join('');$('detailContent').innerHTML=`${body}<div class="file-box"><strong>Adjuntos y fotografías</strong>${canWrite()?`<input type="file" id="detailFile" class="full-input space-top"><button class="primary-btn space-top" onclick="uploadFile('${resource}','${id}')">Adjuntar archivo</button>`:''}<div id="attachmentsArea">${atts.length?atts.map(attachmentHTML).join(''):'<div class="empty space-top">Sin adjuntos.</div>'}</div></div>`;$('detailBackdrop').classList.add('show');$('detailModal').classList.add('show')};
async function getAttachments(resource,id){const{data}=await sb.from('attachments').select('*').eq('entity_type',resource).eq('entity_id',id).order('created_at',{ascending:false});return data||[]}
function attachmentHTML(a){return`<div class="attach-item"><div><strong>${esc(a.original_name)}</strong><div class="meta">${Math.round(Number(a.size_bytes||0)/1024)} KB</div></div><div class="actions"><button class="secondary-btn" onclick="openAttachment('${a.storage_path}')">Abrir</button><button class="secondary-btn" onclick="copyToDrive('${a.storage_path}','${esc(a.original_name)}','${esc(a.mime_type)}')">Drive</button></div></div>`}
window.uploadFile=async(resource,id)=>{const f=$('detailFile')?.files?.[0];if(!f)return toast('Seleccioná un archivo');if(f.size>8*1024*1024)return toast('Máximo 8 MB');const safe=f.name.replace(/[^a-zA-Z0-9._-]+/g,'_'),path=`${resource}/${id}/${crypto.randomUUID()}-${safe}`;let r=await sb.storage.from(C.storageBucket).upload(path,f,{contentType:f.type,upsert:false});if(r.error)return toast(r.error.message);const{error}=await sb.from('attachments').insert({entity_type:resource,entity_id:id,original_name:f.name,storage_path:path,mime_type:f.type||'application/octet-stream',size_bytes:f.size,created_by:state.user.id});if(error)return toast(error.message);toast('Archivo adjuntado');openDetails(resource,id)}
window.openAttachment=async path=>{const{data,error}=await sb.storage.from(C.storageBucket).createSignedUrl(path,300);if(error)return toast(error.message);window.open(data.signedUrl,'_blank')}

const CHECKLIST=[
 ['Organización','Definir fecha','Alta'],['Organización','Confirmar lugar','Alta'],['Organización','Confirmar horario','Alta'],['Organización','Confirmar responsables','Alta'],['Organización','Solicitar autorizaciones','Media'],['Organización','Coordinar instituciones','Media'],['Organización','Confirmar participantes','Media'],
 ['Logística','Solicitar locomoción','Alta'],['Logística','Solicitar sonido / amplificación','Alta'],['Logística','Solicitar escenario','Media'],['Logística','Solicitar mesas','Media'],['Logística','Solicitar sillas','Media'],['Logística','Coordinar electricidad','Media'],['Logística','Coordinar tránsito','Alta'],['Logística','Coordinar limpieza','Media'],['Logística','Coordinar seguridad','Media'],['Logística','Preparar materiales','Alta'],['Logística','Resolver hidratación / alimentación','Media'],
 ['Comunicación','Crear afiche','Alta'],['Comunicación','Crear publicación Instagram','Media'],['Comunicación','Crear historias','Media'],['Comunicación','Difusión WhatsApp','Media'],['Comunicación','Publicar agenda web','Media'],['Comunicación','Contactar medios','Media'],['Comunicación','Enviar recordatorio a participantes','Alta'],
 ['Día del evento','Verificar montaje','Alta'],['Día del evento','Confirmar responsables','Alta'],['Día del evento','Registrar participantes','Media'],['Día del evento','Registro fotográfico','Media'],['Día del evento','Registro audiovisual','Media'],
 ['Después','Enviar agradecimientos','Baja'],['Después','Publicar resultados','Media'],['Después','Guardar fotografías','Baja'],['Después','Evaluar actividad','Media'],['Después','Registrar cantidad final de participantes','Media'],['Después','Elaborar informe','Media']
];
window.openChecklist=async eventId=>{const e=state.events.find(x=>x.id===eventId),{data}=await sb.from('event_checklist_items').select('*').eq('event_id',eventId).order('sort_order');$('detailEyebrow').textContent='CHECKLIST DEL EVENTO';$('detailTitle').textContent=e?.name||'Evento';if(!(data||[]).length)$('detailContent').innerHTML=`<div class="empty">Este evento todavía no tiene checklist.${canWrite()?`<br><button class="primary-btn space-top" onclick="generateChecklist('${eventId}')">Generar checklist completa</button>`:''}</div>`;else $('detailContent').innerHTML=checklistHTML(data);$('detailBackdrop').classList.add('show');$('detailModal').classList.add('show')}
function checklistHTML(items){const g={};items.forEach(x=>(g[x.category]??=[]).push(x));return Object.entries(g).map(([k,list])=>`<section class="check-section"><h3>${esc(k)}</h3>${list.map(x=>`<div class="check-item ${x.status==='Realizada'?'done':''}"><input type="checkbox" ${x.status==='Realizada'?'checked':''} ${canWrite()?'':'disabled'} onchange="toggleChecklist('${x.id}',this.checked)"><div><strong>${esc(x.title)}</strong><div class="meta">${esc(x.priority)} ${x.responsible_name?'· '+esc(x.responsible_name):''}</div></div></div>`).join('')}</section>`).join('')}
window.generateChecklist=async eventId=>{if(!canWrite())return;const rows=CHECKLIST.map(([category,title,priority],i)=>({event_id:eventId,category,title,priority,sort_order:i+1,created_by:state.user.id}));const{error}=await sb.from('event_checklist_items').insert(rows);if(error)return toast(error.message);await sb.from('events').update({checklist_generated:true}).eq('id',eventId);toast('Checklist generada');openChecklist(eventId)}
window.toggleChecklist=async(id,checked)=>{const{error}=await sb.from('event_checklist_items').update({status:checked?'Realizada':'Pendiente',completed_at:checked?new Date().toISOString():null}).eq('id',id);if(error)toast(error.message)}

window.openEventPublic=async eventId=>{const e=state.events.find(x=>x.id===eventId);let{data:s}=await sb.from('event_public_settings').select('*').eq('event_id',eventId).maybeSingle();s=s||{public_enabled:false,registration_enabled:false,capacity:0,require_name:true,require_age_range:true,consent_text:'Declaro que los datos brindados son correctos y autorizo su uso únicamente para la organización de esta actividad.'};const{data:regs}=await sb.from('event_registrations').select('*').eq('event_id',eventId).order('created_at',{ascending:false});$('detailEyebrow').textContent='PORTAL PÚBLICO';$('detailTitle').textContent=e.name;$('detailContent').innerHTML=`<div class="form-grid"><label class="checkbox full"><input id="pePublic" type="checkbox" ${s.public_enabled?'checked':''}> Publicar en Agenda Joven</label><label class="checkbox full"><input id="peReg" type="checkbox" ${s.registration_enabled?'checked':''}> Habilitar inscripción</label><label>Cupos (0 = sin límite)<input id="peCapacity" type="number" value="${s.capacity||0}"></label><label>Título público<input id="peTitle" value="${esc(s.public_title||'')}"></label><label class="full">Descripción pública<textarea id="peDesc" rows="3">${esc(s.public_description||'')}</textarea></label><label>Abre inscripción<input id="peOpen" type="datetime-local" value="${esc((s.registration_open_at||'').slice(0,16))}"></label><label>Cierra inscripción<input id="peClose" type="datetime-local" value="${esc((s.registration_close_at||'').slice(0,16))}"></label><label class="checkbox"><input id="peEmail" type="checkbox" ${s.require_email?'checked':''}> Email obligatorio</label><label class="checkbox"><input id="pePhone" type="checkbox" ${s.require_phone?'checked':''}> Teléfono obligatorio</label><label class="checkbox"><input id="peInst" type="checkbox" ${s.require_institution?'checked':''}> Institución obligatoria</label><label class="checkbox"><input id="peLoc" type="checkbox" ${s.require_locality?'checked':''}> Localidad obligatoria</label><label class="full">Consentimiento<textarea id="peConsent">${esc(s.consent_text||'')}</textarea></label><div class="form-actions"><button type="button" class="primary-btn" onclick="saveEventPublic('${eventId}')">Guardar</button><a class="secondary-btn" href="#/inscripcion/${eventId}">Ver formulario</a></div></div><h3 class="space-top">Inscripciones (${(regs||[]).length})</h3><div class="rows">${(regs||[]).map(r=>`<div class="row"><div><h3>${esc(r.first_name)} ${esc(r.last_name)}</h3><div class="meta">${esc(r.age_range)} · ${esc(r.locality)} · ${esc(r.status)} ${r.checked_in_at?'· ✅':''}</div></div></div>`).join('')||'<div class="empty">Sin inscripciones.</div>'}</div>`;$('detailBackdrop').classList.add('show');$('detailModal').classList.add('show')}
window.saveEventPublic=async eventId=>{const body={event_id:eventId,public_enabled:$('pePublic').checked,registration_enabled:$('peReg').checked,capacity:Number($('peCapacity').value||0),public_title:$('peTitle').value,public_description:$('peDesc').value,registration_open_at:$('peOpen').value||null,registration_close_at:$('peClose').value||null,require_name:true,require_email:$('peEmail').checked,require_phone:$('pePhone').checked,require_institution:$('peInst').checked,require_locality:$('peLoc').checked,require_age_range:true,consent_text:$('peConsent').value};const{error}=await sb.from('event_public_settings').upsert(body);if(error)return toast(error.message);toast('Configuración pública guardada');openEventPublic(eventId)}

async function renderPublic(route){$('publicScreen').classList.remove('hidden');const content=$('publicContent');if(route.startsWith('/agenda'))return publicAgenda(content);if(route.startsWith('/oportunidades'))return publicOpportunities(content);if(route.startsWith('/inscripcion/'))return publicRegistration(content,route.split('/')[2]);if(route.startsWith('/mi-inscripcion/'))return publicMyRegistration(content,route.split('/')[2])}
async function publicAgenda(el){const{data,error}=await sb.from('events').select('id,name,event_date,start_time,end_time,place,address,description,target_audience,event_public_settings(*)').eq('archived',false).order('event_date');if(error)return el.innerHTML=`<div class="empty">${esc(error.message)}</div>`;el.innerHTML=`<section class="public-hero"><p class="eyebrow">JUVENTUD FLORES</p><h1>Agenda Joven</h1><p class="muted">Actividades, talleres y eventos de la Oficina de la Juventud.</p></section><div class="public-cards">${(data||[]).map(e=>{const s=e.event_public_settings?.[0]||e.event_public_settings||{};return`<article class="card"><span class="pill">${fmtDate(e.event_date)}</span><h3>${esc(s.public_title||e.name)}</h3><p class="muted">${esc(e.start_time||'')} ${e.place?'· '+esc(e.place):''}</p><p>${esc(s.public_description||e.description||'')}</p>${s.registration_enabled?`<a class="primary-btn" href="#/inscripcion/${e.id}">Inscribirme</a>`:''}</article>`}).join('')||'<div class="empty">No hay actividades públicas cargadas.</div>'}</div>`}
async function publicOpportunities(el){const{data,error}=await sb.from('opportunities').select('*').eq('public_enabled',true).eq('archived',false).in('status',['Abierta','Próxima']).order('featured',{ascending:false});if(error)return el.innerHTML=`<div class="empty">${esc(error.message)}</div>`;const cats=['Todas',...new Set((data||[]).map(x=>x.category))];el.innerHTML=`<section class="public-hero"><p class="eyebrow">INFORMACIÓN PARA JÓVENES</p><h1>Oportunidades</h1><p class="muted">Becas, trabajo, cursos, estudios, cultura, deportes y participación.</p></section><div id="oppFilters" class="actions space-top">${cats.map((c,i)=>`<button class="${i?'secondary-btn':'primary-btn'}" data-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div><div id="publicOppList" class="public-cards"></div>`;const render=cat=>{$('publicOppList').innerHTML=(cat==='Todas'?data:data.filter(x=>x.category===cat)).map(o=>`<article class="card">${o.featured?'<span class="pill">Destacada</span>':''}<span class="pill">${esc(o.category)}</span><h3>${esc(o.title)}</h3><p class="muted">${esc(o.organization||'')}${o.deadline?' · Cierre '+fmtDate(o.deadline):''}</p><p>${esc(o.summary||o.description||'')}</p><p class="muted">${o.age_min||o.age_max?`Edad: ${o.age_min||'—'} a ${o.age_max||'—'} · `:''}${esc(o.locality||'Todo el país')}</p>${o.external_url?`<a class="primary-btn" target="_blank" rel="noopener" href="${esc(o.external_url)}">Ver oportunidad</a>`:''}</article>`).join('')||'<div class="empty">No hay oportunidades.</div>'};render('Todas');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>render(b.dataset.cat))}
async function publicRegistration(el,eventId){const{data:e,error}=await sb.from('events').select('*,event_public_settings(*)').eq('id',eventId).maybeSingle();if(error||!e)return el.innerHTML='<div class="empty">Actividad no disponible.</div>';const s=e.event_public_settings?.[0]||e.event_public_settings;if(!s?.registration_enabled)return el.innerHTML='<div class="empty">La inscripción no está habilitada.</div>';el.innerHTML=`<section class="public-hero"><p class="eyebrow">INSCRIPCIÓN</p><h1>${esc(s.public_title||e.name)}</h1><p>${esc(s.public_description||e.description||'')}</p><p class="muted">${fmtDate(e.event_date)} · ${esc(e.start_time||'')} · ${esc(e.place||'')}</p></section><form id="publicRegForm" class="public-form"><label>Nombre<input name="first_name" ${s.require_name?'required':''}></label><label>Apellido<input name="last_name"></label><label>Rango de edad<select name="age_range" ${s.require_age_range?'required':''}><option value="">Seleccionar</option><option>Menor de 14</option><option>14–17</option><option>18–24</option><option>25–29</option><option>30 o más</option></select></label><label>Localidad<input name="locality" ${s.require_locality?'required':''}></label><label>Institución / centro educativo<input name="institution" ${s.require_institution?'required':''}></label><label>Email<input name="email" type="email" ${s.require_email?'required':''}></label><label>Teléfono<input name="phone" ${s.require_phone?'required':''}></label><label class="full" style="display:flex;grid-template-columns:auto 1fr;align-items:start"><input name="consent" type="checkbox" required style="width:auto"> ${esc(s.consent_text)}</label><div class="full"><button class="primary-btn" type="submit">Confirmar inscripción</button></div></form>`;$('publicRegForm').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.target),args={p_event_id:eventId,p_first_name:fd.get('first_name')||'',p_last_name:fd.get('last_name')||'',p_age_range:fd.get('age_range')||'',p_locality:fd.get('locality')||'',p_institution:fd.get('institution')||'',p_email:fd.get('email')||'',p_phone:fd.get('phone')||'',p_consent:fd.get('consent')==='on'};const{data,error}=await sb.rpc('register_public_event',args);if(error)return alert(error.message);location.hash='#/mi-inscripcion/'+data[0].public_token}}
async function publicMyRegistration(el,token){const{data,error}=await sb.rpc('get_public_registration',{p_token:token});if(error||!data?.length)return el.innerHTML='<div class="empty">Inscripción no encontrada.</div>';const r=data[0];el.innerHTML=`<section class="success-card"><p class="eyebrow">${r.checked_in_at?'ASISTENCIA REGISTRADA':'INSCRIPCIÓN CONFIRMADA'}</p><h1>${esc(r.event_name)}</h1><p><strong>${esc(r.first_name)} ${esc(r.last_name)}</strong></p><p class="muted">${fmtDate(r.event_date)} · ${esc(r.start_time||'')} · ${esc(r.place||'')}</p><canvas id="publicQr" class="qr-canvas"></canvas><p>Presentá este QR al ingresar.</p><p class="muted small">El QR contiene únicamente un token aleatorio de inscripción.</p></section>`;const url=`${location.origin}${location.pathname}#/mi-inscripcion/${token}`;window.QRCode.toCanvas($('publicQr'),url,{width:280,margin:2})}

function prepareScanner(){$('scannerSupport').textContent=('BarcodeDetector'in window)?'Este navegador permite lectura QR con cámara.':'La lectura de cámara no está disponible en este navegador. Usá el ingreso manual.'}
let qrStream=null,qrTimer=null;
async function startScanner(){if(!('BarcodeDetector'in window))return toast('Usá el ingreso manual en este navegador');try{qrStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});$('qrVideo').srcObject=qrStream;const detector=new BarcodeDetector({formats:['qr_code']});const tick=async()=>{if(!qrStream)return;try{const codes=await detector.detect($('qrVideo'));if(codes.length&&await doCheckin(codes[0].rawValue)){stopScanner();return}}catch{}qrTimer=setTimeout(tick,500)};tick()}catch{toast('No se pudo abrir la cámara')}}
function stopScanner(){if(qrTimer)clearTimeout(qrTimer);if(qrStream)qrStream.getTracks().forEach(t=>t.stop());qrStream=null;$('qrVideo').srcObject=null}
async function doCheckin(raw){let token=String(raw||'').trim();if(token.includes('/mi-inscripcion/'))token=token.split('/mi-inscripcion/').pop().split(/[?#]/)[0];if(token.includes('#/mi-inscripcion/'))token=token.split('#/mi-inscripcion/').pop().split(/[?&]/)[0];const{data,error}=await sb.rpc('check_in_registration',{p_token:token});if(error){$('checkinResult').innerHTML=`<div class="empty">${esc(error.message)}</div>`;return false}const r=data[0];$('checkinResult').innerHTML=`<div class="card"><p class="eyebrow">ASISTENCIA REGISTRADA</p><h3>${esc(r.first_name)} ${esc(r.last_name)}</h3><p>${esc(r.event_name)}</p></div>`;toast('Asistencia registrada');return true}

function renderNotifications(){const unread=state.notifications.filter(n=>!n.read_at);$('notifCount').textContent=unread.length;$('notifCount').classList.toggle('hidden',!unread.length);$('notificationsList').innerHTML=state.notifications.length?state.notifications.map(n=>`<div class="row"><div><h3>${esc(n.title)}</h3><div>${esc(n.message)}</div><div class="meta">${new Date(n.created_at).toLocaleString('es-UY')}</div></div>${!n.read_at?`<button class="secondary-btn" onclick="readNotification('${n.id}')">Leída</button>`:''}</div>`).join(''):'<div class="empty">Sin notificaciones.</div>'}
window.readNotification=async id=>{await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);await loadAll()}
async function readAllNotifications(){const ids=state.notifications.filter(n=>!n.read_at).map(n=>n.id);if(ids.length)await sb.from('notifications').update({read_at:new Date().toISOString()}).in('id',ids);await loadAll()}

async function googleStatus(){try{const{data,error}=await sb.functions.invoke(C.googleFunctions.action,{body:{action:'status'}});state.google=error?{configured:false,connected:false,error:error.message}:data;$('googleStatus').textContent=state.google.connected?'Google conectado.':state.google.configured?'Google configurado, todavía no conectado.':'Edge Functions instaladas. Falta cargar secretos de Google en Supabase.';$('googleConnectBtn').disabled=!state.google.configured}catch(e){$('googleStatus').textContent='Google todavía no configurado.'}}
async function connectGoogle(){const redirectTo=`${location.origin}${location.pathname}#/settings?google=connected`;const{data,error}=await sb.functions.invoke(C.googleFunctions.start,{body:{redirectTo}});if(error)return toast(error.message);location.href=data.url}
window.syncGoogle=async(resource,id)=>{const item=state[resource].find(x=>x.id===id);if(!item)return;const{data,error}=await sb.functions.invoke(C.googleFunctions.action,{body:{action:'calendar_upsert',item,googleEventId:item.google_event_id||''}});if(error||data?.error)return toast(error?.message||data.error);await sb.from(resource).update({google_event_id:data.result.id,google_calendar_id:'primary',...(resource==='tasks'?{google_sync:true}:{})}).eq('id',id);toast('Sincronizado con Google Calendar');await loadAll()}
async function testEmail(){const to=prompt('Destinatario');if(!to)return;const subject=prompt('Asunto','Prueba JUVENTUD FLORES – GESTIÓN');if(!subject)return;const text=prompt('Mensaje','Mensaje enviado desde Juventud Flores mediante Gmail API.');if(text===null)return;const{data,error}=await sb.functions.invoke(C.googleFunctions.action,{body:{action:'gmail_send',to,subject,text}});if(error||data?.error)return toast(error?.message||data.error);toast('Correo enviado')}
window.copyToDrive=async(storagePath,fileName,mimeType)=>{const{data,error}=await sb.functions.invoke(C.googleFunctions.action,{body:{action:'drive_upload',storagePath,fileName,mimeType}});if(error||data?.error)return toast(error?.message||data.error);toast('Archivo copiado a Google Drive')}

async function renderUsers(){if(!isAdmin()){ $('usersCard').classList.add('hidden');return }$('usersCard').classList.remove('hidden');const{data,error}=await sb.from('profiles').select('*').order('created_at');if(error)return;$('usersList').innerHTML=(data||[]).map(u=>`<div class="row"><div><h3>${esc(u.full_name||'Usuario')}</h3><div class="meta">${esc(u.role)} · ${u.active?'Activo':'Pendiente'}</div></div><div class="actions"><select id="role-${u.id}"><option value="consulta" ${u.role==='consulta'?'selected':''}>Consulta</option><option value="equipo" ${u.role==='equipo'?'selected':''}>Equipo</option><option value="admin" ${u.role==='admin'?'selected':''}>Administrador</option></select><button class="secondary-btn" onclick="saveUser('${u.id}',${u.active})">Guardar</button><button class="${u.active?'danger-btn':'primary-btn'}" onclick="toggleUser('${u.id}',${u.active})">${u.active?'Desactivar':'Activar'}</button></div></div>`).join('')}
window.saveUser=async(id,active)=>{const role=$('role-'+id).value,{error}=await sb.from('profiles').update({role,active}).eq('id',id);if(error)return toast(error.message);toast('Usuario actualizado');renderUsers()}
window.toggleUser=async(id,active)=>{if(id===state.user.id&&active&&!confirm('¿Seguro que querés desactivar tu propio usuario?'))return;const{error}=await sb.from('profiles').update({active:!active}).eq('id',id);if(error)return toast(error.message);toast('Usuario actualizado');renderUsers()}

async function loadMemory(){if(!state.profile?.active)return;const y=Number($('memoryYear').value||new Date().getFullYear()),{data}=await sb.from('annual_memory_notes').select('*').eq('year',y).maybeSingle();$('memoryIntro').value=data?.introduction||'';$('memoryHighlights').value=data?.highlights||'';$('memoryChallenges').value=data?.challenges||'';$('memoryPriorities').value=data?.next_year_priorities||''}
async function saveMemory(){if(!canWrite())return toast('Sin permiso de escritura');const y=Number($('memoryYear').value),body={year:y,introduction:$('memoryIntro').value,highlights:$('memoryHighlights').value,challenges:$('memoryChallenges').value,next_year_priorities:$('memoryPriorities').value,updated_by:state.user.id};const{error}=await sb.from('annual_memory_notes').upsert(body);if(error)return toast(error.message);toast('Memoria guardada')}
async function imageDataUrl(path){const r=await fetch(path),b=await r.blob();return new Promise(ok=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.readAsDataURL(b)})}
async function exportPdf(){const{jsPDF}=window.jspdf,doc=new jsPDF(),logo=await imageDataUrl('./assets/logo-juventud-flores.png');doc.addImage(logo,'PNG',15,10,80,22);doc.setFontSize(18);doc.setTextColor(116,16,92);doc.text('INFORME DE GESTIÓN',15,43);doc.setFontSize(10);doc.setTextColor(50,50,55);doc.text(`Fecha: ${fullDate()}`,15,50);const active=state.tasks.filter(t=>!['Realizada','Cancelada'].includes(t.status)),lines=[`Tareas realizadas: ${state.tasks.filter(t=>t.status==='Realizada').length}`,`Tareas pendientes: ${active.length}`,`Esperando respuesta: ${active.filter(t=>t.status==='Esperando respuesta').length}`,`Eventos registrados: ${state.events.length}`,`Reuniones: ${state.meetings.length}`,`Proyectos activos: ${state.projects.filter(p=>!['Finalizado','Cancelado'].includes(p.status)).length}`,`Participación registrada: ${state.participation_records.reduce((a,x)=>a+Number(x.total||0),0)}`];doc.text(lines,15,62);doc.save(`Informe_Juventud_Flores_${isoToday()}.pdf`)}
async function memoryPdf(){const{jsPDF}=window.jspdf,doc=new jsPDF(),logo=await imageDataUrl('./assets/logo-juventud-flores.png'),y=Number($('memoryYear').value);doc.addImage(logo,'PNG',15,10,80,22);doc.setFontSize(19);doc.setTextColor(116,16,92);doc.text(`MEMORIA DE GESTIÓN ${y}`,15,43);doc.setFontSize(10);doc.setTextColor(40,40,45);let yy=55;for(const[title,text]of[['Introducción',$('memoryIntro').value],['Principales logros',$('memoryHighlights').value],['Desafíos',$('memoryChallenges').value],['Prioridades '+(y+1),$('memoryPriorities').value]]){if(!text)continue;doc.setFontSize(14);doc.setTextColor(116,16,92);doc.text(title,15,yy);yy+=7;doc.setFontSize(10);doc.setTextColor(40,40,45);const parts=doc.splitTextToSize(text,180);doc.text(parts,15,yy);yy+=parts.length*5+7;if(yy>270){doc.addPage();yy=20}}doc.save(`Memoria_Juventud_Flores_${y}.pdf`)}
function exportExcel(){const wb=XLSX.utils.book_new(),summary=[['JUVENTUD FLORES – GESTIÓN'],['Fecha',fullDate()],['Tareas',state.tasks.length],['Eventos',state.events.length],['Reuniones',state.meetings.length],['Proyectos',state.projects.length],['Participación',state.participation_records.reduce((a,x)=>a+Number(x.total||0),0)]];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(summary),'Resumen');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.tasks),'Tareas');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.events),'Eventos');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.participation_records),'Participación');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.opportunities),'Oportunidades');XLSX.writeFile(wb,`Juventud_Flores_${isoToday()}.xlsx`)}

$('supabaseStatus').textContent=`Conectado a ${C.supabaseUrl}`;
init().catch(e=>{console.error(e);$('loading').classList.add('hidden');$('authScreen').classList.remove('hidden');toast('No se pudo iniciar la aplicación')});
