(function installPriorityCenter(){
  'use strict';
  if(window.__SORAYA_PRIORITY_CENTER__)return;
  window.__SORAYA_PRIORITY_CENTER__=true;
  const C=window.JF_CONFIG;
  if(!C||!window.supabase)return;
  const db=window.JF_DB||window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const priorityRank={Urgente:4,Alta:3,Media:2,Baja:1};
  const state={profile:null,session:null,rows:[],upcoming:[],scope:'mine',bucket:'now',type:'',loading:false,lastLoad:0};
  function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:C.timezone||'America/Montevideo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
  function addDays(iso,n){const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+n);return new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
  function daysDiff(a,b){if(!a||!b)return null;return Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
  function fmtDate(v){if(!v)return'Sin fecha';try{return new Intl.DateTimeFormat('es-UY',{day:'2-digit',month:'short'}).format(new Date(v+'T12:00:00'))}catch{return v}}
  function fmtTime(v){return v?String(v).slice(0,5):''}
  function activeTask(x){return !['Realizada','Cancelada'].includes(x.status)}
  function activeNote(x){return !['Finalizada','Rechazada'].includes(x.status)}
  function activeCase(x){return !['Resuelto','Cerrado','Archivado'].includes(x.status)}
  function activeMsg(x){return !['Respondida','Finalizada','Archivada'].includes(x.status)}
  function toast(msg){const n=$('toast');if(!n)return;n.textContent=msg;n.classList.add('show');clearTimeout(window.__jfPrioToast);window.__jfPrioToast=setTimeout(()=>n.classList.remove('show'),2600)}
  function safe(result){if(result?.error){console.warn('[Mi prioridad]',result.error);return[]}return result?.data||[]}
  function reasonFor(ref,status,priority,mine,waiting){const d=today(),diff=daysDiff(d,ref),out=[];if(ref&&diff<0)out.push({text:`Vencido hace ${Math.abs(diff)} día${Math.abs(diff)===1?'':'s'}`,tone:'danger'});else if(diff===0)out.push({text:'Vence hoy',tone:'danger'});else if(diff===1)out.push({text:'Vence mañana',tone:'warn'});else if(diff!==null&&diff<=3)out.push({text:`Vence en ${diff} días`,tone:'warn'});else if(diff!==null&&diff<=7)out.push({text:'Esta semana',tone:''});if(priority==='Urgente'||priority==='Alta')out.push({text:`Prioridad ${priority}`,tone:priority==='Urgente'?'danger':'warn'});if(waiting)out.push({text:'Esperando respuesta',tone:''});if(mine)out.push({text:'Asignado a vos',tone:'good'});if(!ref)out.push({text:'Sin fecha',tone:''});if(!out.length&&status)out.push({text:status,tone:''});return out}
  function scoreRow({ref,priority,status,mine,waiting,kind,review=false}){const d=today(),diff=daysDiff(d,ref);let s=(priorityRank[priority]||0)*10+(mine?22:0)+(review?38:0);if(diff!==null){if(diff<0)s+=62+Math.min(24,Math.abs(diff)*2);else if(diff===0)s+=48;else if(diff===1)s+=34;else if(diff<=3)s+=25;else if(diff<=7)s+=14;else if(diff<=14)s+=6}else s-=5;if(waiting){s+=8;if(status==='Esperando respuesta')s-=4}if(kind==='Comunicación')s+=4;if(kind==='Documento')s+=8;return Math.max(0,s)}
  function makeRow(o){const reasons=reasonFor(o.ref,o.status,o.priority,o.mine,o.waiting);return{...o,reasons,score:scoreRow(o)}}
  function ensureShell(){
    const nav=$('mainNav');if(nav&&!nav.querySelector('[data-jf-priority]')){const b=document.createElement('button');b.type='button';b.dataset.jfPriority='1';b.innerHTML='🎯 Mi prioridad <span class="jfprio-nav-count" id="jfPrioNavCount">0</span>';const task=nav.querySelector('[data-view="tasks"]');task?.insertAdjacentElement('afterend',b);b.addEventListener('click',()=>openView())}
    if($('view-priority'))return;
    const tasks=$('view-tasks'),section=document.createElement('section');section.id='view-priority';section.className='view';section.innerHTML=`<div class="page-head"><div><p class="eyebrow">CENTRO DE PENDIENTES INTELIGENTE</p><h1>Mi prioridad</h1><p class="muted">Soraya ordena lo que requiere atención según plazos, urgencia, responsabilidad y estado.</p></div><button type="button" class="secondary-btn" id="jfPrioRefresh">↻ Actualizar</button></div><div id="jfPriorityCenter" class="jfprio"><div class="jfprio-loading">Preparando tus prioridades…</div></div>`;tasks?tasks.insertAdjacentElement('afterend',section):document.querySelector('.main')?.appendChild(section);$('jfPrioRefresh')?.addEventListener('click',()=>load(true))
  }
  function openView(){ensureShell();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-priority')?.classList.add('active');document.querySelectorAll('#mainNav button').forEach(b=>b.classList.remove('active'));document.querySelector('#mainNav [data-jf-priority]')?.classList.add('active');$('sidebar')?.classList.remove('open');history.replaceState(null,'','#/priority');if(Date.now()-state.lastLoad>120000)load(false);else render()}
  function openRow(row){if(!row)return;if(['tasks','notes','meetings','events'].includes(row.resource)&&window.openDetails){window.openDetails(row.resource,row.id);return}if(row.resource==='cases82'){document.querySelector('#mainNav [data-view="cases82"]')?.click();setTimeout(()=>{const x=$('jf82CaseSearch');if(x){x.value=row.search||row.title;x.dispatchEvent(new Event('input',{bubbles:true}))}},120);return}if(row.resource==='inbox82'){document.querySelector('#mainNav [data-view="inbox82"]')?.click();setTimeout(()=>{const x=$('jf82MsgSearch');if(x){x.value=row.search||row.title;x.dispatchEvent(new Event('input',{bubbles:true}))}},120);return}if(row.resource==='officialdocs84'){document.querySelector('#mainNav [data-view="officialdocs84"]')?.click();return}if(row.resource==='google'){if(row.link)window.open(row.link,'_blank','noopener');else document.querySelector('#mainNav [data-view="calendar"]')?.click()}}
  async function load(force=false){
    if(state.loading)return;if(!force&&state.lastLoad&&Date.now()-state.lastLoad<60000){render();return}state.loading=true;ensureShell();$('jfPriorityCenter')?.classList.add('jfprio-refreshing');
    try{const {data:{session}}=await db.auth.getSession();state.session=session;if(!session?.user)return;const uid=session.user.id;const p=await db.from('profiles').select('id,full_name,role,active').eq('id',uid).maybeSingle();state.profile=p.data||null;
      const d=today(),next14=addDays(d,14);const [tasksR,assignR,notesR,casesR,msgR,docsR,gR,meetR,eventR]=await Promise.all([
        db.from('tasks').select('id,title,status,priority,task_date,task_time,deadline,followup_date,waiting_since,next_action,responsible_id,institution_name,project_name,created_by,updated_at').eq('archived',false).limit(1500),
        db.from('task_assignments').select('task_id,user_id,status,assignment_role').eq('user_id',uid).limit(1000),
        db.from('notes').select('id,subject,status,note_date,followup_date,responsible_id,responsible_name,recipient,department,updated_at').eq('archived',false).limit(1000),
        db.from('institutional_cases').select('id,case_number,title,status,priority,due_date,assigned_to,assigned_name,institution_name,workflow_stage,updated_at').eq('archived',false).limit(1000),
        db.from('institutional_messages').select('id,subject,status,priority,response_due_date,assigned_to,assigned_name,institution_name,direction,updated_at').eq('archived',false).limit(1000),
        db.from('generated_documents').select('id,title,document_type,official_number,official_status,workflow_status,current_reviewer_id,current_reviewer_name,issue_date,updated_at').eq('archived',false).limit(1000),
        db.from('google_sync_items').select('id,source,title,item_date,status,completed,html_link,soraya_id,soraya_table').eq('user_id',uid).eq('source','tasks').eq('archived',false).eq('completed',false).limit(1000),
        db.from('meetings').select('id,subject,meeting_date,meeting_time,place').eq('archived',false).gte('meeting_date',d).lte('meeting_date',next14).order('meeting_date'),
        db.from('events').select('id,name,event_date,start_time,place,responsible_id,responsible_name').eq('archived',false).gte('event_date',d).lte('event_date',next14).order('event_date')
      ]);
      const assigned=new Set(safe(assignR).filter(a=>!['Completada','Rechazada'].includes(a.status)).map(a=>a.task_id)),rows=[];
      safe(tasksR).filter(activeTask).forEach(x=>{const ref=x.deadline||x.followup_date||x.task_date||'',mine=x.responsible_id===uid||assigned.has(x.id),waiting=x.status==='Esperando respuesta'||!!x.waiting_since;rows.push(makeRow({kind:'Tarea',resource:'tasks',id:x.id,title:x.title,ref,priority:x.priority,status:x.status,mine,waiting,owner:x.institution_name||x.project_name||'',detail:x.next_action||'',search:x.title}))});
      safe(notesR).filter(activeNote).forEach(x=>{const ref=x.followup_date||'',mine=x.responsible_id===uid,waiting=x.status==='Esperando respuesta';rows.push(makeRow({kind:'Nota',resource:'notes',id:x.id,title:x.subject,ref,priority:'',status:x.status,mine,waiting,owner:x.recipient||x.department||'',detail:x.responsible_name||'',search:x.subject}))});
      safe(casesR).filter(activeCase).forEach(x=>{const mine=x.assigned_to===uid;rows.push(makeRow({kind:'Expediente',resource:'cases82',id:x.id,title:x.title,ref:x.due_date||'',priority:x.priority,status:x.status,mine,waiting:x.status==='Esperando respuesta',owner:x.institution_name||x.assigned_name||'',detail:x.case_number||x.workflow_stage||'',search:x.case_number||x.title}))});
      safe(msgR).filter(activeMsg).forEach(x=>{const mine=x.assigned_to===uid;rows.push(makeRow({kind:'Comunicación',resource:'inbox82',id:x.id,title:x.subject,ref:x.response_due_date||'',priority:x.priority,status:x.status,mine,waiting:x.status==='Esperando respuesta',owner:x.institution_name||x.assigned_name||'',detail:x.direction||'',search:x.subject}))});
      safe(docsR).forEach(x=>{const mine=x.current_reviewer_id===uid;if(!mine)return;const finished=['Aprobado','Firmado','Archivado','Anulado','Enviado'].includes(x.official_status)||['Aprobado','Finalizado'].includes(x.workflow_status);if(finished)return;rows.push(makeRow({kind:'Documento',resource:'officialdocs84',id:x.id,title:x.title,ref:x.issue_date||'',priority:'Alta',status:x.workflow_status||x.official_status||'Pendiente de revisión',mine:true,waiting:false,review:true,owner:x.current_reviewer_name||'',detail:x.official_number||x.document_type||'',search:x.official_number||x.title}))});
      safe(gR).forEach(x=>{if(x.soraya_id)return;rows.push(makeRow({kind:'Google Task',resource:'google',id:x.id,title:x.title,ref:x.item_date||'',priority:'',status:x.status||'Pendiente',mine:true,waiting:false,owner:'Google Tasks',detail:'',link:x.html_link||''}))});
      state.rows=rows.sort((a,b)=>b.score-a.score||(a.ref||'9999').localeCompare(b.ref||'9999'));
      const up=[];safe(meetR).forEach(x=>up.push({kind:'Reunión',resource:'meetings',id:x.id,title:x.subject,date:x.meeting_date,time:x.meeting_time,place:x.place||''}));safe(eventR).forEach(x=>up.push({kind:'Evento',resource:'events',id:x.id,title:x.name,date:x.event_date,time:x.start_time,place:x.place||'',mine:x.responsible_id===uid}));state.upcoming=up.sort((a,b)=>a.date.localeCompare(b.date)||String(a.time||'').localeCompare(String(b.time||'')));state.lastLoad=Date.now();render();
    }catch(e){console.error('[Mi prioridad]',e);const box=$('jfPriorityCenter');if(box)box.innerHTML=`<div class="jfprio-empty">No se pudo cargar el centro de prioridades. <button class="secondary-btn" id="jfPrioRetry">Reintentar</button></div>`;$('jfPrioRetry')?.addEventListener('click',()=>load(true));}
    finally{state.loading=false;$('jfPriorityCenter')?.classList.remove('jfprio-refreshing')}
  }
  function scopeRows(){return state.scope==='mine'?state.rows.filter(x=>x.mine):state.rows}
  function inBucket(x,b){const d=today(),diff=daysDiff(d,x.ref);if(b==='overdue')return diff!==null&&diff<0;if(b==='today')return diff===0;if(b==='week')return diff!==null&&diff>=0&&diff<=7;if(b==='waiting')return x.waiting;if(b==='nodate')return !x.ref;if(b==='all')return true;return x.score>=45||(diff!==null&&diff<=3)||x.kind==='Documento'}
  function filtered(){return scopeRows().filter(x=>inBucket(x,state.bucket)).filter(x=>!state.type||x.kind===state.type).sort((a,b)=>b.score-a.score||(a.ref||'9999').localeCompare(b.ref||'9999'))}
  function focus(){const mine=state.rows.filter(x=>x.mine);return mine[0]||state.rows[0]||null}
  function countBucket(b,rows=scopeRows()){return rows.filter(x=>inBucket(x,b)).length}
  function render(){const box=$('jfPriorityCenter');if(!box)return;const rows=filtered(),f=focus(),allScope=scopeRows(),types=[...new Set(state.rows.map(x=>x.kind))].sort();const unassigned=state.rows.filter(x=>!x.mine&&!x.owner).length,waiting=countBucket('waiting',allScope),overdue=countBucket('overdue',allScope),week=countBucket('week',allScope);const fReasons=f?f.reasons:[];
    box.innerHTML=`<div class="jfprio-hero"><section class="jfprio-focus"><div class="jfprio-focus-top"><div><p class="jfprio-kicker">${f?.mine?'TU FOCO RECOMENDADO':'PRIORIDAD DEL EQUIPO'}</p><h2>${f?esc(f.title):'No hay pendientes críticos'}</h2><p>${f?`${esc(f.kind)}${f.owner?' · '+esc(f.owner):''}`:'Soraya no detecta urgencias en este momento.'}</p></div>${f?`<div class="jfprio-score"><strong>${Math.round(f.score)}</strong><span>prioridad</span></div>`:''}</div>${f?`<div class="jfprio-reasons">${fReasons.map(r=>`<span class="jfprio-reason ${r.tone||''}">${esc(r.text)}</span>`).join('')}</div><div class="jfprio-focus-actions"><button type="button" class="primary-btn" data-jfprio-open="${esc(f.id)}">Ir a resolver →</button><button type="button" class="secondary-btn" data-jfprio-bucket="all">Ver toda la cola</button></div>`:''}</section><aside class="jfprio-health"><h3>Estado de tus pendientes</h3><div class="jfprio-health-grid"><div><strong>${overdue}</strong><span>vencidos</span></div><div><strong>${waiting}</strong><span>esperando</span></div><div><strong>${week}</strong><span>esta semana</span></div><div><strong>${unassigned}</strong><span>sin responsable</span></div></div></aside></div><div class="jfprio-toolbar"><div class="jfprio-tabs">${[['now','Ahora'],['overdue','Vencidos'],['today','Hoy'],['week','Esta semana'],['waiting','Esperando'],['nodate','Sin fecha'],['all','Todo']].map(([k,l])=>`<button type="button" class="jfprio-tab ${state.bucket===k?'active':''}" data-jfprio-bucket="${k}">${l} <span>${countBucket(k)}</span></button>`).join('')}</div><div class="jfprio-toolbar-right"><div class="jfprio-scope"><button type="button" class="${state.scope==='mine'?'active':''}" data-jfprio-scope="mine">Lo mío</button><button type="button" class="${state.scope==='team'?'active':''}" data-jfprio-scope="team">Equipo</button></div><select id="jfPrioType"><option value="">Todos los tipos</option>${types.map(t=>`<option ${state.type===t?'selected':''}>${esc(t)}</option>`).join('')}</select></div></div><section class="jfprio-panel"><div class="jfprio-panel-head"><div><h2>Cola inteligente</h2><p>Ordenada por plazo, urgencia, responsabilidad y necesidad de intervención.</p></div><span class="jfprio-count">${rows.length}</span></div><div class="jfprio-list">${rows.length?rows.map((x,i)=>rowHtml(x,i)).join(''):'<div class="jfprio-empty">No hay pendientes para este filtro.</div>'}</div></section>${upcomingHtml()}`;
    bindRender();updateNavCount();
  }
  function rowHtml(x,i){const d=daysDiff(today(),x.ref),tone=d!==null&&d<0?'danger':(d!==null&&d<=1)||x.priority==='Urgente'?'warn':'';const why=x.reasons.slice(0,3).map(r=>r.text).join(' · ');return`<article class="jfprio-row ${tone}"><div class="jfprio-rank">${i+1}</div><div class="jfprio-copy"><strong>${esc(x.title)}</strong><div class="jfprio-meta"><span class="jfprio-type">${esc(x.kind)}</span>${x.ref?`<span>${esc(fmtDate(x.ref))}</span>`:'<span>Sin fecha</span>'}${x.owner?`<span>${esc(x.owner)}</span>`:''}${x.detail?`<span>${esc(x.detail)}</span>`:''}</div><div class="jfprio-why">${esc(why)}</div></div><div class="jfprio-row-actions"><button type="button" data-jfprio-open="${esc(x.id)}">Abrir</button></div></article>`}
  function upcomingHtml(){const d=today(),items=state.upcoming.filter(x=>x.date>=d&&x.date<=addDays(d,7)).slice(0,9);if(!items.length)return'';return`<section class="jfprio-panel"><div class="jfprio-panel-head"><div><h2>Compromisos próximos</h2><p>Reuniones y eventos de los próximos 7 días.</p></div></div><div class="jfprio-upcoming">${items.map(x=>`<button type="button" class="jfprio-upcoming-card" data-jfprio-upcoming="${esc(x.resource)}|${esc(x.id)}"><b>${esc(x.title)}</b><span>${esc(fmtDate(x.date))}${x.time?' · '+esc(fmtTime(x.time)):''}${x.place?' · '+esc(x.place):''}</span></button>`).join('')}</div></section>`}
  function bindRender(){const box=$('jfPriorityCenter');box?.querySelectorAll('[data-jfprio-bucket]').forEach(b=>b.addEventListener('click',()=>{state.bucket=b.dataset.jfprioBucket;render()}));box?.querySelectorAll('[data-jfprio-scope]').forEach(b=>b.addEventListener('click',()=>{state.scope=b.dataset.jfprioScope;render()}));$('jfPrioType')?.addEventListener('change',e=>{state.type=e.target.value;render()});box?.querySelectorAll('[data-jfprio-open]').forEach(b=>b.addEventListener('click',()=>openRow(state.rows.find(x=>x.id===b.dataset.jfprioOpen))));box?.querySelectorAll('[data-jfprio-upcoming]').forEach(b=>b.addEventListener('click',()=>{const[r,id]=b.dataset.jfprioUpcoming.split('|');if(window.openDetails)window.openDetails(r,id)}))}
  function updateNavCount(){const n=$('jfPrioNavCount');if(n)n.textContent=String(state.rows.filter(x=>x.mine&&inBucket(x,'now')).length)}
  function boot(){ensureShell();setTimeout(()=>load(false),1800);window.addEventListener('jf:data-changed',()=>{state.lastLoad=0;if($('view-priority')?.classList.contains('active'))load(true)});window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#/priority'))setTimeout(openView,40)})}
  boot();window.SorayaPriority={open:openView,refresh:()=>load(true),get rows(){return state.rows}};
})();