(function installQuickAdd(){
  if(window.__JF_QUICK_ADD__) return;
  window.__JF_QUICK_ADD__=true;
  const C=window.JF_CONFIG;if(!window.supabase||!C)return;
  const db=window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:C.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  let menu=null,profile=null,session=null,lastProfileCheck=0;

  function toast(msg){const n=$('toast');if(n){n.textContent=msg;n.classList.add('show');clearTimeout(window.__jfqaToast);window.__jfqaToast=setTimeout(()=>n.classList.remove('show'),2500)}else alert(msg)}
  async function ensureProfile(){if(profile&&Date.now()-lastProfileCheck<60000)return profile;const{data:{session:s}}=await db.auth.getSession();session=s;if(!s?.user)return null;const{data}=await db.from('profiles').select('id,full_name,role,active').eq('id',s.user.id).maybeSingle();profile=data||null;lastProfileCheck=Date.now();return profile}
  const canWrite=()=>profile?.active&&['admin','equipo'].includes(profile.role);

  function build(){
    if(menu)return menu;
    menu=document.createElement('div');menu.className='jf-quickadd-menu';menu.id='jfQuickAddMenu';menu.setAttribute('role','menu');menu.setAttribute('aria-label','Carga ultrarrápida');
    const items=[
      ['task','✅','Tarea','Pendiente o seguimiento'],['meeting','🤝','Reunión','Fecha, hora y compromisos'],['event','🎪','Evento','Actividad o jornada'],['note','📄','Nota','Nota o solicitud'],['message','📥','Comunicación','Entrada o salida institucional'],['case','🗂️','Expediente','Solicitud o trámite'],['reminder','⏰','Recordatorio','Aviso rápido con fecha']
    ];
    menu.innerHTML=`<div class="jf-quickadd-head"><div><strong>Agregar rápido</strong><span>Elegí qué querés registrar</span></div><button class="jf-quickadd-close" type="button" aria-label="Cerrar">×</button></div><div class="jf-quickadd-grid">${items.map(([k,i,t,s],idx)=>`<button type="button" class="jf-quickadd-item ${idx===6?'full':''}" data-jfqa="${k}" role="menuitem"><span class="jf-quickadd-icon">${i}</span><span class="jf-quickadd-copy"><strong>${t}</strong><small>${s}</small></span></button>`).join('')}</div><div class="jf-quickadd-foot">Se abre el formulario correspondiente sin perder tu trabajo actual.</div>`;
    document.body.appendChild(menu);
    menu.querySelector('.jf-quickadd-close').onclick=close;
    menu.addEventListener('click',e=>{const b=e.target.closest('[data-jfqa]');if(b)choose(b.dataset.jfqa)});
    document.addEventListener('pointerdown',e=>{if(menu?.classList.contains('open')&&!menu.contains(e.target)&&e.target!==$('quickAddBtn')&&!e.target.closest?.('#quickAddBtn')&&!e.target.closest?.('[data-jf-mobile="__add__"]'))close()});
    document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
    window.addEventListener('resize',position);
    return menu;
  }
  function position(){const b=$('quickAddBtn');if(!menu||!b||!menu.classList.contains('open')||matchMedia('(max-width:700px)').matches)return;const r=b.getBoundingClientRect();const w=320;let left=Math.min(innerWidth-w-14,Math.max(14,r.right-w));menu.style.left=left+'px';menu.style.top=(r.bottom+8)+'px';menu.style.right='auto';menu.style.bottom='auto'}
  async function toggle(e){e?.preventDefault();e?.stopPropagation();await ensureProfile();if(!canWrite())return toast('Tu rol es solo de consulta');build();if(menu.classList.contains('open'))return close();menu.classList.add('open');$('quickAddBtn')?.setAttribute('aria-expanded','true');position();setTimeout(()=>menu.querySelector('[data-jfqa]')?.focus(),0)}
  function close(){if(!menu)return;menu.classList.remove('open');$('quickAddBtn')?.setAttribute('aria-expanded','false')}

  function openBase(resource){if(typeof window.editEntity!=='function')return toast('El formulario todavía se está cargando');window.editEntity(resource);setTimeout(()=>document.querySelector('#entityForm input, #entityForm textarea, #entityForm select')?.focus(),30)}
  function openReminder(){openBase('tasks');setTimeout(()=>{const f=$('entityForm');if(!f)return;const cat=f.elements.category;if(cat){if(![...cat.options].some(o=>o.value==='Recordatorio'))cat.add(new Option('Recordatorio','Recordatorio'));cat.value='Recordatorio'}if(f.elements.status)f.elements.status.value='Pendiente';if(f.elements.priority)f.elements.priority.value='Media';if(f.elements.task_date&&!f.elements.task_date.value)f.elements.task_date.value=today();if(f.elements.reminder)f.elements.reminder.value='Mismo día';if(f.elements.title){f.elements.title.placeholder='Ej.: Llamar a INJU';f.elements.title.focus()}$('modalEyebrow').textContent='RECORDATORIO';$('modalTitle').textContent='Nuevo recordatorio'},40)}

  function openDetail(title,body){$('detailEyebrow').textContent='CARGA RÁPIDA';$('detailTitle').textContent=title;$('detailContent').innerHTML=body;$('detailBackdrop').classList.add('show');$('detailModal').classList.add('show')}
  function personOptions(rows){return '<option value="">Sin asignar</option>'+rows.filter(p=>['admin','equipo'].includes(p.role)).map(p=>`<option value="${p.id}">${esc(p.full_name)}</option>`).join('')}
  function institutionOptions(rows){return '<option value="">Sin institución vinculada</option>'+rows.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('')}
  function projectOptions(rows){return '<option value="">Sin proyecto</option>'+rows.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}
  async function dependencies(){const[p,i,pr]=await Promise.all([db.from('profiles').select('id,full_name,role,active').eq('active',true).order('full_name'),db.from('institutions').select('id,name').eq('archived',false).order('name'),db.from('projects').select('id,name').eq('archived',false).order('name')]);return{people:p.data||[],institutions:i.data||[],projects:pr.data||[]}}

  async function openMessage(){const d=await dependencies();openDetail('Registrar comunicación',`<form id="jfqaMessageForm" class="form-grid"><label>Dirección<select name="direction"><option>Entrada</option><option>Salida</option></select></label><label>Fecha<input name="registered_date" type="date" value="${today()}" required></label><label>Hora<input name="registered_time" type="time"></label><label>Canal<select name="channel"><option>Email</option><option>Nota</option><option>WhatsApp</option><option>Teléfono</option><option>Presencial</option><option>Formulario</option><option>Otro</option></select></label><label>Remitente<input name="sender"></label><label>Destinatario<input name="recipient"></label><label class="full">Institución<select name="institution_id">${institutionOptions(d.institutions)}</select></label><label class="full">Asunto<input name="subject" required autofocus></label><label class="full">Resumen<textarea name="summary" rows="3"></textarea></label><label>Estado<select name="status"><option>Nueva</option><option>En gestión</option><option>Esperando respuesta</option><option>Respondida</option><option>Finalizada</option></select></label><label>Prioridad<select name="priority"><option>Media</option><option>Urgente</option><option>Alta</option><option>Baja</option></select></label><label>Responsable<select name="assigned_to">${personOptions(d.people)}</select></label><label>Responder antes de<input name="response_due_date" type="date"></label><label class="full">Referencia externa<input name="external_reference"></label><div class="jf-quickadd-form-note">Podés completar solo los datos esenciales ahora y ampliar el registro después desde Bandeja institucional.</div><div class="form-actions"><button type="button" class="secondary-btn" data-cancel>Cancelar</button><button class="primary-btn">Guardar comunicación</button></div></form>`);const f=$('jfqaMessageForm');f.querySelector('[data-cancel]').onclick=()=>window.closeDetail?.();f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),inst=d.institutions.find(x=>x.id===fd.get('institution_id')),person=d.people.find(x=>x.id===fd.get('assigned_to'));const body={direction:fd.get('direction'),registered_date:fd.get('registered_date'),registered_time:fd.get('registered_time')||null,channel:fd.get('channel'),sender:fd.get('sender'),recipient:fd.get('recipient'),institution_id:fd.get('institution_id')||null,institution_name:inst?.name||'',subject:fd.get('subject'),summary:fd.get('summary'),status:fd.get('status'),priority:fd.get('priority'),assigned_to:fd.get('assigned_to')||null,assigned_name:person?.full_name||'',response_due_date:fd.get('response_due_date')||null,external_reference:fd.get('external_reference'),created_by:session.user.id};const{error}=await db.from('institutional_messages').insert(body);if(error)return toast(error.message);window.closeDetail?.();toast('Comunicación registrada')}}

  async function openCase(){const d=await dependencies();openDetail('Nuevo expediente / solicitud',`<form id="jfqaCaseForm" class="form-grid"><label class="full">Tema / título<input name="title" required autofocus></label><label>Tipo<select name="case_type"><option>Solicitud</option><option>Expediente</option><option>Convenio</option><option>Evento</option><option>Proyecto</option><option>Consulta</option><option>Reclamo</option><option>Otro</option></select></label><label>Prioridad<select name="priority"><option>Media</option><option>Urgente</option><option>Alta</option><option>Baja</option></select></label><label>Estado<select name="status"><option>Abierto</option><option>En análisis</option><option>En trámite</option><option>Esperando respuesta</option><option>Resuelto</option><option>Cerrado</option></select></label><label>Fecha apertura<input name="opened_date" type="date" value="${today()}"></label><label>Fecha límite<input name="due_date" type="date"></label><label>Institución<select name="institution_id">${institutionOptions(d.institutions)}</select></label><label>Proyecto<select name="project_id">${projectOptions(d.projects)}</select></label><label>Responsable<select name="assigned_to">${personOptions(d.people)}</select></label><label class="full">Descripción<textarea name="description" rows="4"></textarea></label><div class="jf-quickadd-form-note">El número institucional del expediente se generará automáticamente al guardar.</div><div class="form-actions"><button type="button" class="secondary-btn" data-cancel>Cancelar</button><button class="primary-btn">Crear expediente</button></div></form>`);const f=$('jfqaCaseForm');f.querySelector('[data-cancel]').onclick=()=>window.closeDetail?.();f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),inst=d.institutions.find(x=>x.id===fd.get('institution_id')),person=d.people.find(x=>x.id===fd.get('assigned_to'));const body={title:fd.get('title'),case_type:fd.get('case_type'),priority:fd.get('priority'),status:fd.get('status'),opened_date:fd.get('opened_date'),due_date:fd.get('due_date')||null,institution_id:fd.get('institution_id')||null,institution_name:inst?.name||'',project_id:fd.get('project_id')||null,assigned_to:fd.get('assigned_to')||null,assigned_name:person?.full_name||'',description:fd.get('description'),created_by:session.user.id};const{error}=await db.from('institutional_cases').insert(body);if(error)return toast(error.message);window.closeDetail?.();toast('Expediente creado')}}

  async function choose(kind){close();await ensureProfile();if(!canWrite())return toast('Tu rol es solo de consulta');if(kind==='task')return openBase('tasks');if(kind==='meeting')return openBase('meetings');if(kind==='event')return openBase('events');if(kind==='note')return openBase('notes');if(kind==='reminder')return openReminder();if(kind==='message')return openMessage();if(kind==='case')return openCase()}

  function bind(){const b=$('quickAddBtn');if(!b)return;b.setAttribute('aria-haspopup','menu');b.setAttribute('aria-expanded','false');b.onclick=toggle;const mobile=document.querySelector('[data-jf-mobile="__add__"]');if(mobile&&!mobile.dataset.jfqaBound){mobile.dataset.jfqaBound='1';mobile.onclick=e=>{e.preventDefault();e.stopPropagation();toggle(e)}}}
  function scan(){bind();if($('app')?.classList.contains('hidden'))close()}
  build();scan();setTimeout(scan,300);setTimeout(scan,1200);new MutationObserver(()=>requestAnimationFrame(scan)).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
  window.JFQuickAdd={open:toggle,close};
})();
