(function installQuickTask(){
  if(window.__JF_QUICK_TASK__) return;
  window.__JF_QUICK_TASK__=true;
  const C=window.JF_CONFIG;if(!window.supabase||!C)return;
  const db=window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const months={enero:0,febrero:1,marzo:2,abril:3,mayo:4,junio:5,julio:6,agosto:7,septiembre:8,setiembre:8,octubre:9,noviembre:10,diciembre:11};
  const weekdays={domingo:0,lunes:1,martes:2,miercoles:3,miércoles:3,jueves:4,viernes:5,sabado:6,sábado:6};
  let session=null,profile=null,kind='task',timer=null;
  function norm(s=''){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
  function isoLocal(d){return new Intl.DateTimeFormat('en-CA',{timeZone:C.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
  function today(){return isoLocal(new Date())}
  function dateFromIso(iso){return new Date(iso+'T12:00:00')}
  function addDays(iso,n){const d=dateFromIso(iso);d.setDate(d.getDate()+n);return isoLocal(d)}
  function currentHour(){return Number(new Intl.DateTimeFormat('en-GB',{timeZone:C.timezone,hour:'2-digit',hour12:false}).format(new Date()))}
  function toast(msg){const n=$('toast');if(n){n.textContent=msg;n.classList.add('show');clearTimeout(window.__jfqtToast);window.__jfqtToast=setTimeout(()=>n.classList.remove('show'),2600)}else alert(msg)}
  async function auth(){const{data:{session:s}}=await db.auth.getSession();session=s;if(!s?.user)return null;const{data}=await db.from('profiles').select('id,full_name,role,active').eq('id',s.user.id).maybeSingle();profile=data||null;return profile}
  const canWrite=()=>profile?.active&&['admin','equipo'].includes(profile.role);

  function parseDate(raw){const n=norm(raw),base=today();let match,label='';
    if(/\bpasado\s+manana\b/.test(n))return{value:addDays(base,2),label:'Pasado mañana'};
    if(/\bmanana\b/.test(n))return{value:addDays(base,1),label:'Mañana'};
    if(/\bhoy\b/.test(n))return{value:base,label:'Hoy'};
    match=n.match(/\ben\s+(\d+)\s+dias?\b/);if(match)return{value:addDays(base,Number(match[1])),label:`En ${match[1]} días`};
    if(/\ben\s+una\s+semana\b/.test(n))return{value:addDays(base,7),label:'En una semana'};
    match=n.match(/\b(\d{1,2})[\/-](\d{1,2})(?:[\/-](\d{2,4}))?\b/);if(match){let y=match[3]?Number(match[3]):Number(base.slice(0,4));if(y<100)y+=2000;const m=String(Number(match[2])).padStart(2,'0'),d=String(Number(match[1])).padStart(2,'0');return{value:`${y}-${m}-${d}`,label:`${d}/${m}/${y}`}}
    match=n.match(/\b(\d{1,2})\s+de\s+(enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|setiembre|octubre|noviembre|diciembre)(?:\s+de\s+(\d{4}))?\b/);if(match){const y=Number(match[3]||base.slice(0,4)),m=String(months[match[2]]+1).padStart(2,'0'),d=String(Number(match[1])).padStart(2,'0');return{value:`${y}-${m}-${d}`,label:`${d}/${m}/${y}`}}
    match=n.match(/\b(?:(proximo|proxima|este|esta|el)\s+)?(lunes|martes|miercoles|jueves|viernes|sabado|domingo)\b/);if(match){const target=weekdays[match[2]],d=dateFromIso(base),cur=d.getDay();let delta=(target-cur+7)%7;const prefix=match[1]||'';if((prefix==='proximo'||prefix==='proxima')&&delta===0)delta=7;d.setDate(d.getDate()+delta);return{value:isoLocal(d),label:(prefix==='proximo'||prefix==='proxima'?'Próximo ':'')+match[2]}}
    return{value:'',label:''}
  }
  function parseTime(raw){const n=norm(raw);let m;
    if(/\bmediodia\b/.test(n))return{value:'12:00',label:'12:00'};
    if(/\bmedianoche\b/.test(n))return{value:'00:00',label:'00:00'};
    m=n.match(/\b(?:a\s+las?|a\s+la)\s+(\d{1,2})(?::(\d{2}))?\s*(?:hs?|h)?\b/);if(!m)m=n.match(/\b(\d{1,2}):(\d{2})\s*(?:hs?|h)?\b/);if(!m)m=n.match(/\b(\d{1,2})\s*(?:hs|hrs|horas)\b/);if(!m)return{value:'',label:''};let h=Number(m[1]),min=Number(m[2]||0);if(h>23||min>59)return{value:'',label:''};return{value:`${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}`,label:`${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}`}
  }
  function parsePriority(raw){const n=norm(raw);if(/\burgente\b|\bprioridad\s+urgente\b/.test(n))return{value:'Urgente',label:'Urgente'};if(/\bprioridad\s+alta\b|\balta\s+prioridad\b|\bimportante\b/.test(n)||/(?:^|\s)alta[.!?,]?\s*$/.test(n))return{value:'Alta',label:'Alta'};if(/\bprioridad\s+baja\b|\bbaja\s+prioridad\b/.test(n)||/(?:^|\s)baja[.!?,]?\s*$/.test(n))return{value:'Baja',label:'Baja'};if(/\bprioridad\s+media\b|\bmedia\s+prioridad\b/.test(n)||/(?:^|\s)media[.!?,]?\s*$/.test(n))return{value:'Media',label:'Media'};return{value:'Media',label:''}}
  function inferCategory(raw){const n=norm(raw);if(kind==='reminder')return'Recordatorio';if(/\b(llamar|llamada|telefono|telefonica)\b/.test(n))return'Llamada';if(/\b(whatsapp|wsp)\b/.test(n))return'WhatsApp';if(/\b(email|correo|mail)\b/.test(n))return'Email';if(/\b(reunion|reunir|entrevista)\b/.test(n))return'Reunión';if(/\b(nota|oficio|solicitud)\b/.test(n))return'Nota';if(/\b(locomocion|traslado|vehiculo)\b/.test(n))return'Locomoción';if(/\b(difundir|difusion|publicar|post|reel|instagram|redes)\b/.test(n))return'Difusión';if(/\b(comprar|compra|adquirir)\b/.test(n))return'Compra';if(/\b(presupuesto|cotizacion|cotizar)\b/.test(n))return'Presupuesto';if(/\b(coordinar|coordinacion)\b/.test(n))return'Coordinación institucional';if(/\b(evento|actividad|jornada|taller)\b/.test(n))return'Actividad';return'Seguimiento'}
  function cleanTitle(raw){let s=String(raw||'').trim();const patterns=[/\bpasado\s+mañana\b/gi,/\bmañana\b/gi,/\bhoy\b/gi,/\ben\s+\d+\s+d[ií]as?\b/gi,/\ben\s+una\s+semana\b/gi,/\b\d{1,2}[\/-]\d{1,2}(?:[\/-]\d{2,4})?\b/g,/\b\d{1,2}\s+de\s+(?:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|setiembre|octubre|noviembre|diciembre)(?:\s+de\s+\d{4})?\b/gi,/\b(?:(?:pr[oó]ximo|pr[oó]xima|este|esta|el)\s+)?(?:lunes|martes|mi[eé]rcoles|jueves|viernes|s[aá]bado|domingo)\b/gi,/\b(?:a\s+las?|a\s+la)\s+\d{1,2}(?::\d{2})?\s*(?:hs?|h)?\b/gi,/\b\d{1,2}:\d{2}\s*(?:hs?|h)?\b/gi,/\b\d{1,2}\s*(?:hs|hrs|horas)\b/gi,/\bmediod[ií]a\b/gi,/\bmedianoche\b/gi,/\bprioridad\s+(?:urgente|alta|media|baja)\b/gi,/\b(?:alta|media|baja)\s+prioridad\b/gi,/\burgente\b/gi,/\bimportante\b/gi];patterns.forEach(r=>s=s.replace(r,' '));s=s.replace(/\s+/g,' ').replace(/\s+([,.!?])/g,'$1').replace(/^[,;:\-\s]+|[,;:\-\s]+$/g,'').trim();s=s.replace(/\s+(alta|media|baja)$/i,'').trim();return s||String(raw||'').trim()}
  function parse(raw){const date=parseDate(raw),time=parseTime(raw),priority=parsePriority(raw),category=inferCategory(raw);return{title:cleanTitle(raw),task_date:date.value,task_time:time.value,priority:priority.value,category,reminder:kind==='reminder'?'Mismo día':'',detected:{date:date.label,time:time.label,priority:priority.label,category}}}

  function modal(title,html){$('detailEyebrow').textContent='CARGA INTELIGENTE · SIN IA';$('detailTitle').textContent=title;$('detailContent').innerHTML=html;$('detailBackdrop').classList.add('show');$('detailModal').classList.add('show')}
  function renderChips(p){const box=$('jfqtDetected');if(!box)return;const chips=[];if(p.detected.date)chips.push(`<span class="jfqt-chip blue">📅 ${esc(p.detected.date)}</span>`);if(p.detected.time)chips.push(`<span class="jfqt-chip blue">🕐 ${esc(p.detected.time)}</span>`);if(p.detected.priority)chips.push(`<span class="jfqt-chip ${p.priority==='Urgente'?'red':'orange'}">⚑ ${esc(p.priority)}</span>`);chips.push(`<span class="jfqt-chip">🏷 ${esc(p.category)}</span>`);box.innerHTML=chips.join('')}
  function applyParse(){const phrase=$('jfqtPhrase')?.value||'',p=parse(phrase);if($('jfqtTitle'))$('jfqtTitle').value=p.title;if($('jfqtDate'))$('jfqtDate').value=p.task_date;if($('jfqtTime'))$('jfqtTime').value=p.task_time;if($('jfqtPriority'))$('jfqtPriority').value=p.priority;if($('jfqtCategory')){if(![...$('jfqtCategory').options].some(o=>o.value===p.category))$('jfqtCategory').add(new Option(p.category,p.category));$('jfqtCategory').value=p.category}if($('jfqtReminder'))$('jfqtReminder').value=p.reminder;renderChips(p);updateSummary()}
  function updateSummary(){const t=$('jfqtTitle')?.value||'Sin título',d=$('jfqtDate')?.value||'Sin fecha',h=$('jfqtTime')?.value||'Sin hora',p=$('jfqtPriority')?.value||'Media',c=$('jfqtCategory')?.value||'Seguimiento';if($('jfqtSummary'))$('jfqtSummary').innerHTML=`<strong>${esc(t)}</strong><br>${esc(d)} · ${esc(h)} · ${esc(p)} · ${esc(c)}`}
  function example(text){if($('jfqtPhrase')){$('jfqtPhrase').value=text;applyParse();$('jfqtPhrase').focus()}}

  async function open(k='task'){
    kind=k==='reminder'?'reminder':'task';await auth();if(!canWrite())return toast('Tu rol es solo de consulta');
    const isRem=kind==='reminder',title=isRem?'Nuevo recordatorio rápido':'Nueva tarea rápida';
    const cats=['Seguimiento','Reunión','Evento','Taller','Actividad','Nota','Solicitud','Locomoción','Llamada','WhatsApp','Email','Convenio','Difusión','Redes sociales','Capacitación','Proyecto','Compra','Presupuesto','Coordinación institucional','Recordatorio','Otro'];
    modal(title,`<div class="jfqt-wrap"><div class="jfqt-sentence"><label>Escribí la tarea como la dirías normalmente<textarea id="jfqtPhrase" placeholder="Ej.: Llamar a Ana mañana a las 10 urgente" autofocus></textarea></label><div class="jfqt-help">Se interpreta únicamente en tu navegador. No se envía a OpenAI ni a ningún servicio de IA.</div><div class="jfqt-example"><button type="button" data-ex="Llamar a Ana mañana a las 10 urgente">Ejemplo 1</button><button type="button" data-ex="Enviar correo a INJU el viernes a las 14 prioridad alta">Ejemplo 2</button><button type="button" data-ex="Coordinar locomoción pasado mañana 9:30">Ejemplo 3</button></div></div><div id="jfqtDetected" class="jfqt-detected"></div><div class="jfqt-preview"><label class="title">Título<input id="jfqtTitle"></label><label>Fecha<input id="jfqtDate" type="date"></label><label>Hora<input id="jfqtTime" type="time"></label><label>Prioridad<select id="jfqtPriority"><option>Urgente</option><option>Alta</option><option selected>Media</option><option>Baja</option></select></label><label>Categoría<select id="jfqtCategory">${cats.map(c=>`<option>${c}</option>`).join('')}</select></label>${isRem?'<label>Recordatorio<select id="jfqtReminder"><option>Mismo día</option><option>1 día antes</option><option>2 días antes</option><option>3 días antes</option><option>7 días antes</option><option>2 horas antes</option></select></label>':'<input id="jfqtReminder" type="hidden" value="">'}<label>Asignación<select id="jfqtAssign"><option value="self">Asignarme a mí</option><option value="none">Dejar sin responsable</option></select></label><label>Estado<select id="jfqtStatus"><option>Pendiente</option><option>En proceso</option><option>Esperando respuesta</option><option>Agendada</option><option>Confirmada</option></select></label></div><div id="jfqtSummary" class="jfqt-summary"></div><div class="jfqt-actions"><button id="jfqtFull" type="button" class="secondary-btn">Formulario completo</button><button id="jfqtCancel" type="button" class="secondary-btn">Cancelar</button><button id="jfqtSave" type="button" class="primary-btn">Guardar ${isRem?'recordatorio':'tarea'}</button></div></div>`);
    const phrase=$('jfqtPhrase');phrase.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(applyParse,180)});document.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>example(b.dataset.ex));['jfqtTitle','jfqtDate','jfqtTime','jfqtPriority','jfqtCategory','jfqtReminder','jfqtStatus'].forEach(id=>$(id)?.addEventListener('change',updateSummary));$('jfqtCancel').onclick=()=>window.closeDetail?.();$('jfqtSave').onclick=save;$('jfqtFull').onclick=openFull;applyParse();setTimeout(()=>phrase.focus(),50)
  }
  async function save(){if(!session?.user)return toast('Sesión no disponible');const title=$('jfqtTitle')?.value.trim();if(!title)return toast('Escribí un título o una frase');const body={title,description:'',category:$('jfqtCategory').value||'Seguimiento',status:$('jfqtStatus').value||'Pendiente',priority:$('jfqtPriority').value||'Media',task_date:$('jfqtDate').value||null,task_time:$('jfqtTime').value||null,deadline:null,responsible_id:$('jfqtAssign').value==='self'?session.user.id:null,reminder:$('jfqtReminder')?.value||'',notes:'',created_by:session.user.id};const{error}=await db.from('tasks').insert(body);if(error)return toast(error.message);window.closeDetail?.();toast(kind==='reminder'?'Recordatorio creado':'Tarea creada');window.dispatchEvent(new CustomEvent('jf:data-changed',{detail:{resource:'tasks'}}));setTimeout(()=>{if((location.hash||'#/dashboard').includes('dashboard'))window.dispatchEvent(new HashChangeEvent('hashchange'))},120)}
  function openFull(){const parsed={title:$('jfqtTitle')?.value||'',task_date:$('jfqtDate')?.value||'',task_time:$('jfqtTime')?.value||'',priority:$('jfqtPriority')?.value||'Media',category:$('jfqtCategory')?.value||'Seguimiento',reminder:$('jfqtReminder')?.value||'',status:$('jfqtStatus')?.value||'Pendiente'};window.closeDetail?.();if(typeof window.editEntity!=='function')return toast('El formulario completo todavía se está cargando');window.editEntity('tasks');setTimeout(()=>{const f=$('entityForm');if(!f)return;Object.entries(parsed).forEach(([k,v])=>{if(f.elements[k]&&v!==undefined)f.elements[k].value=v});f.elements.title?.focus()},60)}

  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-jfqa="task"],[data-jfqa="reminder"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();window.JFQuickAdd?.close?.();open(b.dataset.jfqa)},true);
  window.JFQuickTask={open,parse};
})();
