(function installQuickAddV2(){
  if(window.__JF_QUICK_ADD_V2__) return;
  window.__JF_QUICK_ADD_V2__=true;
  const C=window.JF_CONFIG;if(!C)return;
  const db=window.JF_DB||((typeof sb!=='undefined'&&sb)||window.supabase?.createClient(C.supabaseUrl,C.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}));
  if(!db)return;
  const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[s]));
  const stateRef=()=>window.JF_APP_STATE||(typeof state!=='undefined'?state:null);
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:C.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  let menu=null,peopleCache=null,peopleAt=0;

  function toast(msg){try{if(typeof window.toast==='function')return window.toast(msg)}catch{}const n=$('toast');if(n){n.textContent=msg;n.classList.add('show');clearTimeout(window.__jfqa2Toast);window.__jfqa2Toast=setTimeout(()=>n.classList.remove('show'),2200)}}
  async function profile(){const s=stateRef();if(s?.profile?.active)return s.profile;const{data:{session}}=await db.auth.getSession();if(!session?.user)return null;const{data}=await db.from('profiles').select('id,full_name,role,active').eq('id',session.user.id).maybeSingle();return data||null}
  async function canWrite(){const p=await profile();return !!(p?.active&&['admin','equipo'].includes(p.role))}
  async function people(){if(peopleCache&&Date.now()-peopleAt<300000)return peopleCache;const{data}=await db.from('profiles').select('id,full_name,role,active').eq('active',true).in('role',['admin','equipo']).order('full_name');peopleCache=data||[];peopleAt=Date.now();return peopleCache}
  function depsLocal(){const s=stateRef();return{institutions:s?.institutions||[],projects:s?.projects||[]}}
  function personOptions(rows){return '<option value="">Sin asignar</option>'+rows.map(p=>`<option value="${p.id}">${esc(p.full_name)}</option>`).join('')}
  function institutionOptions(rows){return '<option value="">Sin institución vinculada</option>'+rows.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('')}
  function projectOptions(rows){return '<option value="">Sin proyecto</option>'+rows.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}

  function build(){if(menu)return menu;menu=document.createElement('div');menu.id='jfQuickAddMenu';menu.className='jf-quickadd-menu';menu.setAttribute('role','menu');menu.setAttribute('aria-label','Carga ultrarrápida');const items=[['task','✅','Tarea','Pendiente o seguimiento'],['meeting','🤝','Reunión','Fecha, hora y coordinación'],['event','🎪','Evento','Actividad o jornada'],['note','📄','Nota','Nota o solicitud'],['message','📥','Comunicación','Entrada o salida institucional'],['case','🗂️','Expediente','Solicitud o trámite'],['reminder','⏰','Recordatorio','Aviso rápido con fecha']];menu.innerHTML=`<div class="jf-quickadd-head"><div><strong>Agregar rápido</strong><span>Elegí qué querés registrar</span></div><button class="jf-quickadd-close" type="button" aria-label="Cerrar">×</button></div><div class="jf-quickadd-grid">${items.map(([k,i,t,s],idx)=>`<button type="button" class="jf-quickadd-item ${idx===6?'full':''}" data-jfqa="${k}" role="menuitem"><span class="jf-quickadd-icon">${i}</span><span class="jf-quickadd-copy"><strong>${t}</strong><small>${s}</small></span></button>`).join('')}</div><div class="jf-quickadd-foot">Carga directa, sin recargar el sistema.</div>`;document.body.appendChild(menu);menu.querySelector('.jf-quickadd-close').onclick=close;menu.addEventListener('click',e=>{const b=e.target.closest('[data-jfqa]');if(b)choose(b.dataset.jfqa)});return menu}
  function position(){const b=$('quickAddBtn');if(!menu||!b||!menu.classList.contains('open')||matchMedia('(max-width:700px)').matches)return;const r=b.getBoundingClientRect(),w=320;menu.style.left=Math.min(innerWidth-w-14,Math.max(14,r.right-w))+'px';menu.style.top=(r.bottom+8)+'px';menu.style.right='auto';menu.style.bottom='auto'}
  async function toggle(e){e?.preventDefault();e?.stopPropagation();if(!(await canWrite()))return toast('Tu rol es solo de consulta');build();menu.classList.toggle('open');$('quickAddBtn')?.setAttribute('aria-expanded',menu.classList.contains('open')?'true':'false');if(menu.classList.contains('open')){position();requestAnimationFrame(()=>menu.querySelector('[data-jfqa]')?.focus())}}
  function close(){if(!menu)return;menu.classList.remove('open');$('quickAddBtn')?.setAttribute('aria-expanded','false')}
  function openBase(resource){if(typeof window.editEntity!=='function')return toast('El formulario todavía se está cargando');window.editEntity(resource);requestAnimationFrame(()=>document.querySelector('#entityForm input,#entityForm textarea,#entityForm select')?.focus())}
  function openDetail(title,body){$('detailEyebrow').textContent='CARGA RÁPIDA';$('detailTitle').textContent=title;$('detailContent').innerHTML=body;$('detailBackdrop').classList.add('show');$('detailModal').classList.add('show')}

  async function openMessage(){const users=await people(),d=depsLocal(),s=stateRef();openDetail('Registrar comunicación',`<form id="jfqa2Message" class="form-grid"><label>Dirección<select name="direction"><option>Entrada</option><option>Salida</option></select></label><label>Fecha<input name="registered_date" type="date" value="${today()}" required></label><label>Canal<select name="channel"><option>Email</option><option>Nota</option><option>WhatsApp</option><option>Teléfono</option><option>Presencial</option><option>Formulario</option><option>Otro</option></select></label><label>Prioridad<select name="priority"><option>Media</option><option>Urgente</option><option>Alta</option><option>Baja</option></select></label><label class="full">Institución<select name="institution_id">${institutionOptions(d.institutions)}</select></label><label class="full">Asunto<input name="subject" required autofocus></label><label>Remitente<input name="sender"></label><label>Destinatario<input name="recipient"></label><label>Responsable<select name="assigned_to">${personOptions(users)}</select></label><label>Responder antes de<input name="response_due_date" type="date"></label><label class="full">Resumen<textarea name="summary" rows="3"></textarea></label><div class="form-actions"><button type="button" class="secondary-btn" data-cancel>Cancelar</button><button class="primary-btn" type="submit">Guardar comunicación</button></div></form>`);const f=$('jfqa2Message');f.querySelector('[data-cancel]').onclick=()=>window.closeDetail?.();f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('[type=submit]'),old=btn.textContent;btn.disabled=true;btn.textContent='Guardando…';const fd=new FormData(f),inst=d.institutions.find(x=>x.id===fd.get('institution_id')),person=users.find(x=>x.id===fd.get('assigned_to'));const body={direction:fd.get('direction'),registered_date:fd.get('registered_date'),channel:fd.get('channel'),sender:fd.get('sender')||'',recipient:fd.get('recipient')||'',institution_id:fd.get('institution_id')||null,institution_name:inst?.name||'',subject:fd.get('subject'),summary:fd.get('summary')||'',status:'Nueva',priority:fd.get('priority'),assigned_to:fd.get('assigned_to')||null,assigned_name:person?.full_name||'',response_due_date:fd.get('response_due_date')||null,created_by:s?.user?.id||null};const{error}=await db.from('institutional_messages').insert(body);if(error){btn.disabled=false;btn.textContent=old;return toast(error.message)}window.closeDetail?.();toast('Comunicación registrada');window.dispatchEvent(new CustomEvent('jf:data-changed',{detail:{resource:'institutional_messages'}}))}}

  async function openCase(){const users=await people(),d=depsLocal(),s=stateRef();openDetail('Nuevo expediente / solicitud',`<form id="jfqa2Case" class="form-grid"><label class="full">Tema / título<input name="title" required autofocus></label><label>Tipo<select name="case_type"><option>Solicitud</option><option>Expediente</option><option>Convenio</option><option>Evento</option><option>Proyecto</option><option>Consulta</option><option>Reclamo</option><option>Otro</option></select></label><label>Prioridad<select name="priority"><option>Media</option><option>Urgente</option><option>Alta</option><option>Baja</option></select></label><label>Fecha límite<input name="due_date" type="date"></label><label>Institución<select name="institution_id">${institutionOptions(d.institutions)}</select></label><label>Proyecto<select name="project_id">${projectOptions(d.projects)}</select></label><label>Responsable<select name="assigned_to">${personOptions(users)}</select></label><label class="full">Descripción<textarea name="description" rows="4"></textarea></label><div class="form-actions"><button type="button" class="secondary-btn" data-cancel>Cancelar</button><button class="primary-btn" type="submit">Crear expediente</button></div></form>`);const f=$('jfqa2Case');f.querySelector('[data-cancel]').onclick=()=>window.closeDetail?.();f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('[type=submit]'),old=btn.textContent;btn.disabled=true;btn.textContent='Guardando…';const fd=new FormData(f),inst=d.institutions.find(x=>x.id===fd.get('institution_id')),person=users.find(x=>x.id===fd.get('assigned_to'));const body={title:fd.get('title'),case_type:fd.get('case_type'),priority:fd.get('priority'),status:'Abierto',opened_date:today(),due_date:fd.get('due_date')||null,institution_id:fd.get('institution_id')||null,institution_name:inst?.name||'',project_id:fd.get('project_id')||null,assigned_to:fd.get('assigned_to')||null,assigned_name:person?.full_name||'',description:fd.get('description')||'',created_by:s?.user?.id||null};const{error}=await db.from('institutional_cases').insert(body);if(error){btn.disabled=false;btn.textContent=old;return toast(error.message)}window.closeDetail?.();toast('Expediente creado');window.dispatchEvent(new CustomEvent('jf:data-changed',{detail:{resource:'institutional_cases'}}))}}

  async function choose(kind){close();if(kind==='task')return window.JFQuickTask?.open?.('task')||openBase('tasks');if(kind==='reminder')return window.JFQuickTask?.open?.('reminder')||openBase('tasks');if(kind==='meeting')return window.JFQuickSchedule?.open?.('meeting')||openBase('meetings');if(kind==='event')return window.JFQuickSchedule?.open?.('event')||openBase('events');if(kind==='note')return openBase('notes');if(kind==='message')return openMessage();if(kind==='case')return openCase()}

  build();
  document.addEventListener('click',e=>{const trigger=e.target.closest?.('#quickAddBtn,[data-jf-mobile="__add__"]');if(trigger){e.preventDefault();e.stopPropagation();toggle(e);return}if(menu?.classList.contains('open')&&!menu.contains(e.target))close()},true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
  window.addEventListener('resize',position,{passive:true});
  window.JFQuickAdd={open:toggle,close};
})();