(function installStage83(){
  if(window.__JF_STAGE83__) return;
  window.__JF_STAGE83__=true;
  const C=window.JF_CONFIG;
  if(!window.supabase||!C) return;
  const db=window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[s]));
  const fmtDate=v=>{if(!v)return 'Sin fecha';try{return new Intl.DateTimeFormat('es-UY',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(String(v).slice(0,10)+'T12:00:00'))}catch{return String(v)}};
  const fmtDateTime=v=>{if(!v)return '';try{return new Intl.DateTimeFormat('es-UY',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:C.timezone}).format(new Date(v))}catch{return String(v)}};
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:C.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const openStatuses=new Set(['Pendiente','Aceptada','En proceso']);
  let session=null,profile=null,profiles=[],cases=[],messages=[],documents=[],tasks=[],agenda=[],assignments=[],derivations=[],approvals=[],audits=[];

  async function auth(){const{data:{session:s}}=await db.auth.getSession();session=s;if(!s?.user){profile=null;return null}const{data}=await db.from('profiles').select('id,full_name,role,active').eq('id',s.user.id).maybeSingle();profile=data||null;return profile}
  const canWrite=()=>profile?.active&&['admin','equipo'].includes(profile.role);
  const isAdmin=()=>profile?.active&&profile.role==='admin';
  function toast(msg){const n=$('toast');if(n){n.textContent=msg;n.classList.add('show');clearTimeout(window.__jf83toast);window.__jf83toast=setTimeout(()=>n.classList.remove('show'),2600)}else alert(msg)}
  function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id.replace('view-','')));$('sidebar')?.classList.remove('open');history.replaceState(null,'','#/'+id.replace('view-',''))}
  function modal(title,html){$('detailEyebrow').textContent='ETAPA 8.3';$('detailTitle').textContent=title;$('detailContent').innerHTML=html;$('detailBackdrop').classList.add('show');$('detailModal').classList.add('show')}
  function closeModal(){$('detailBackdrop').classList.remove('show');$('detailModal').classList.remove('show')}
  function staffOptions(selected=''){return profiles.filter(p=>['admin','equipo'].includes(p.role)).map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(p.full_name)} · ${p.role==='admin'?'Administrador':'Equipo'}</option>`).join('')}
  function entityLabel(type){return{case:'Expediente',message:'Comunicación',document:'Documento',task:'Tarea'}[type]||type}
  function entityTitle(type,id){const list={case:cases,message:messages,document:documents,task:tasks}[type]||[];const x=list.find(v=>v.id===id);if(!x)return 'Registro';return type==='case'?`${x.case_number} · ${x.title}`:type==='message'?x.subject:type==='document'?x.title:x.title}
  function stageClass(s=''){return String(s).toLowerCase().replaceAll(' ','-').replaceAll('ó','o').replaceAll('á','a').replaceAll('í','i')}

  function inject(){
    const main=document.querySelector('.main'),nav=$('mainNav');if(!main||!nav)return;
    if(!$('view-workflow83')){
      const holder=document.createElement('div');holder.innerHTML=`
      <section id="view-workflow83" class="view">
        <div class="page-head"><div><p class="eyebrow">ETAPA 8.3 · FLUJO INSTITUCIONAL</p><h1>Trámites y derivaciones</h1><p class="muted">Estados formales, responsables, derivaciones internas y plazos.</p></div>${canWrite()?'<button id="jf83NewDerivation" class="primary-btn">＋ Derivar gestión</button>':''}</div>
        <div id="jf83WorkflowStats" class="stats"></div>
        <div class="jf83-toolbar"><select id="jf83StageFilter"><option value="">Todas las etapas</option>${['Recepción','Análisis','Derivado','Esperando respuesta','En elaboración','Para aprobación','Aprobado','Resuelto','Cerrado'].map(x=>`<option>${x}</option>`).join('')}</select><input id="jf83CaseSearch" placeholder="Buscar expediente o institución"></div>
        <div class="grid two"><article class="card span2"><p class="eyebrow">EXPEDIENTES</p><h2>Estado de trámites</h2><div id="jf83Cases"></div></article><article class="card"><p class="eyebrow">PARA MÍ</p><h2>Derivaciones recibidas</h2><div id="jf83Incoming"></div></article><article class="card"><p class="eyebrow">ENVIADAS</p><h2>Derivaciones realizadas</h2><div id="jf83Outgoing"></div></article></div>
      </section>
      <section id="view-approvals83" class="view">
        <div class="page-head"><div><p class="eyebrow">DOCUMENTOS</p><h1>Aprobaciones y visto bueno</h1><p class="muted">Revisión, aprobación y firma interna con registro de persona, fecha y decisión.</p></div>${canWrite()?'<button id="jf83NewApproval" class="primary-btn">＋ Solicitar revisión</button>':''}</div>
        <div class="jf83-legal-note"><strong>Firma interna / visto bueno.</strong> Este circuito registra aprobación interna; no sustituye una firma electrónica avanzada o certificado digital cuando estos sean jurídicamente exigibles.</div>
        <div id="jf83ApprovalStats" class="stats"></div>
        <div class="grid two"><article class="card"><p class="eyebrow">ACCIÓN REQUERIDA</p><h2>Pendientes para mí</h2><div id="jf83MyApprovals"></div></article><article class="card"><p class="eyebrow">DOCUMENTOS</p><h2>Estado documental</h2><div id="jf83Documents"></div></article></div>
      </section>
      <section id="view-mywork83" class="view">
        <div class="page-head"><div><p class="eyebrow">PANEL PERSONAL</p><h1>Mi trabajo</h1><p class="muted">Todo lo que está asignado a tu usuario en un solo lugar.</p></div><button id="jf83RefreshMyWork" class="secondary-btn">Actualizar</button></div>
        <div id="jf83MyStats" class="stats"></div><div class="grid two"><article class="card"><h2>Prioridad personal</h2><div id="jf83MyPriority"></div></article><article class="card"><h2>Carga del equipo</h2><div id="jf83TeamLoad"></div></article><article class="card span2"><h2>Agenda y responsabilidades</h2><div id="jf83MyTimeline"></div></article></div>
      </section>
      <section id="view-audit83" class="view">
        <div class="page-head"><div><p class="eyebrow">TRAZABILIDAD</p><h1>Historial institucional</h1><p class="muted">Quién hizo qué, sobre qué registro y cuándo.</p></div><button id="jf83RefreshAudit" class="secondary-btn">Actualizar</button></div>
        <div class="jf83-toolbar"><select id="jf83AuditActor"><option value="">Todas las personas</option></select><select id="jf83AuditType"><option value="">Todos los registros</option><option value="case">Expedientes</option><option value="institutional_cases">Expedientes</option><option value="message">Comunicaciones</option><option value="institutional_messages">Comunicaciones</option><option value="document">Documentos</option><option value="generated_documents">Documentos</option><option value="task_assignments">Asignaciones</option><option value="task">Tareas</option></select><input id="jf83AuditSearch" placeholder="Buscar acción, estado o detalle"></div><div id="jf83AuditList" class="jf83-audit"></div>
      </section>`;
      const settings=$('view-settings');[...holder.children].forEach(x=>settings?main.insertBefore(x,settings):main.appendChild(x));
    }
    const defs=[['workflow83','🔀 Trámites'],['approvals83','✍️ Aprobaciones'],['mywork83','👤 Mi trabajo'],['audit83','🕘 Historial']];
    defs.forEach(([v,label])=>{if($('jf83Nav-'+v))return;const b=document.createElement('button');b.id='jf83Nav-'+v;b.dataset.view=v;b.textContent=label;const settings=nav.querySelector('[data-view="settings"]');settings?nav.insertBefore(b,settings):nav.appendChild(b);b.onclick=async()=>{setView('view-'+v);await refresh(v)}});
    bind();
  }

  function bind(){
    if($('jf83NewDerivation')&&!$('jf83NewDerivation').dataset.bound){$('jf83NewDerivation').dataset.bound='1';$('jf83NewDerivation').onclick=openDerivationForm}
    if($('jf83NewApproval')&&!$('jf83NewApproval').dataset.bound){$('jf83NewApproval').dataset.bound='1';$('jf83NewApproval').onclick=openApprovalForm}
    if($('jf83RefreshMyWork')&&!$('jf83RefreshMyWork').dataset.bound){$('jf83RefreshMyWork').dataset.bound='1';$('jf83RefreshMyWork').onclick=()=>refresh('mywork83')}
    if($('jf83RefreshAudit')&&!$('jf83RefreshAudit').dataset.bound){$('jf83RefreshAudit').dataset.bound='1';$('jf83RefreshAudit').onclick=()=>refresh('audit83')}
    if($('jf83StageFilter')&&!$('jf83StageFilter').dataset.bound){$('jf83StageFilter').dataset.bound='1';$('jf83StageFilter').onchange=renderCases;$('jf83CaseSearch').oninput=renderCases}
    ['jf83AuditActor','jf83AuditType'].forEach(id=>{if($(id)&&!$(id).dataset.bound){$(id).dataset.bound='1';$(id).onchange=renderAudit}});if($('jf83AuditSearch')&&!$('jf83AuditSearch').dataset.bound){$('jf83AuditSearch').dataset.bound='1';$('jf83AuditSearch').oninput=renderAudit}
  }

  async function loadBase(){
    await auth();if(!profile?.active)return;
    const rs=await Promise.all([
      db.from('profiles').select('id,full_name,role,active').eq('active',true).order('full_name'),
      db.from('institutional_cases').select('*').eq('archived',false).order('updated_at',{ascending:false}).limit(500),
      db.from('institutional_messages').select('*').eq('archived',false).order('updated_at',{ascending:false}).limit(500),
      db.from('generated_documents').select('*').eq('archived',false).order('updated_at',{ascending:false}).limit(500),
      db.from('tasks').select('id,title,status,priority,task_date,task_time,deadline,responsible_id,institution_name,project_name').eq('archived',false).order('updated_at',{ascending:false}).limit(700),
      db.from('team_agenda_items').select('*').eq('archived',false).order('item_date').limit(500),
      db.from('task_assignments').select('*').order('updated_at',{ascending:false}).limit(800),
      db.from('workflow_derivations').select('*').order('created_at',{ascending:false}).limit(500),
      db.from('document_approvals').select('*').order('requested_at',{ascending:false}).limit(500)
    ]);
    profiles=rs[0].data||[];cases=rs[1].data||[];messages=rs[2].data||[];documents=rs[3].data||[];tasks=rs[4].data||[];agenda=rs[5].data||[];assignments=rs[6].data||[];derivations=rs[7].data||[];approvals=rs[8].data||[];
  }
  async function loadAudit(){const{data,error}=await db.from('workflow_audit_events').select('*').order('created_at',{ascending:false}).limit(700);if(error){toast(error.message);audits=[]}else audits=data||[]}
  async function refresh(v){await loadBase();if(v==='workflow83'){renderCases();renderDerivations()}if(v==='approvals83')renderApprovals();if(v==='mywork83')renderMyWork();if(v==='audit83'){await loadAudit();fillAuditFilters();renderAudit()}}

  function renderCases(){
    const box=$('jf83Cases');if(!box)return;const st=$('jf83StageFilter')?.value||'',q=($('jf83CaseSearch')?.value||'').toLowerCase();let rows=cases.filter(x=>(!st||x.workflow_stage===st)&&(!q||[x.case_number,x.title,x.institution_name,x.assigned_name].join(' ').toLowerCase().includes(q)));const overdue=cases.filter(x=>x.due_date&&x.due_date<today()&&!['Cerrado','Resuelto'].includes(x.workflow_stage)).length;$('jf83WorkflowStats').innerHTML=`<div class="stat"><span>Trámites activos</span><strong>${cases.filter(x=>x.workflow_stage!=='Cerrado').length}</strong></div><div class="stat"><span>Para aprobación</span><strong>${cases.filter(x=>x.workflow_stage==='Para aprobación').length}</strong></div><div class="stat alert"><span>Vencidos</span><strong>${overdue}</strong></div><div class="stat"><span>Cerrados</span><strong>${cases.filter(x=>x.workflow_stage==='Cerrado').length}</strong></div>`;box.innerHTML=rows.length?rows.map(x=>`<div class="jf83-row"><div><div class="jf83-line"><span class="jf83-stage ${stageClass(x.workflow_stage)}">${esc(x.workflow_stage||'Recepción')}</span><span class="badge ${esc(x.priority)}">${esc(x.priority)}</span></div><h3>${esc(x.case_number)} · ${esc(x.title)}</h3><p class="meta">${esc(x.institution_name||'Sin institución')} · ${x.assigned_name?`Responsable: ${esc(x.assigned_name)}`:'Sin responsable'} ${x.due_date?'· vence '+fmtDate(x.due_date):''}</p></div><div class="jf83-actions">${canWrite()?`<button class="secondary-btn" onclick="JF83.changeCaseStage('${x.id}')">Cambiar etapa</button><button class="secondary-btn" onclick="JF83.derive('case','${x.id}')">Derivar</button>`:''}<button class="secondary-btn" onclick="JF83.entityHistory('case','${x.id}')">Historial</button></div></div>`).join(''):'<div class="empty">No hay expedientes para este filtro.</div>'
  }

  function renderDerivations(){
    const incoming=derivations.filter(x=>x.to_user===profile.id&&openStatuses.has(x.status));const outgoing=derivations.filter(x=>x.from_user===profile.id).slice(0,20);
    $('jf83Incoming').innerHTML=incoming.length?incoming.map(x=>derivationCard(x,true)).join(''):'<div class="empty">No tenés derivaciones pendientes.</div>';
    $('jf83Outgoing').innerHTML=outgoing.length?outgoing.map(x=>derivationCard(x,false)).join(''):'<div class="empty">Todavía no realizaste derivaciones.</div>';
  }
  function derivationCard(x,mine){return `<div class="jf83-mini"><div><strong>${esc(entityLabel(x.entity_type))}: ${esc(entityTitle(x.entity_type,x.entity_id))}</strong><div class="meta">${esc(x.from_name)} → ${esc(x.to_name)} · ${esc(x.status)} ${x.due_date?'· '+fmtDate(x.due_date):''}</div>${x.note?`<p>${esc(x.note)}</p>`:''}</div>${mine&&canWrite()?`<div class="jf83-actions"><button onclick="JF83.replyDerivation('${x.id}','Aceptada')">Aceptar</button><button onclick="JF83.replyDerivation('${x.id}','En proceso')">En proceso</button><button onclick="JF83.replyDerivation('${x.id}','Devuelta')">Devolver</button><button onclick="JF83.replyDerivation('${x.id}','Finalizada')">Finalizar</button></div>`:''}</div>`}

  function openDerivationForm(type='case',id=''){
    if(!canWrite())return toast('Tu rol es de consulta');const sourceList=type==='case'?cases:type==='message'?messages:type==='document'?documents:tasks;modal('Derivar gestión',`<form id="jf83DeriveForm" class="form-grid"><label>Tipo<select id="jf83DeriveType" name="entity_type"><option value="case" ${type==='case'?'selected':''}>Expediente</option><option value="message" ${type==='message'?'selected':''}>Comunicación</option><option value="document" ${type==='document'?'selected':''}>Documento</option><option value="task" ${type==='task'?'selected':''}>Tarea</option></select></label><label class="full">Registro<select id="jf83DeriveEntity" name="entity_id"></select></label><label>Derivar a<select name="to_user" required>${staffOptions()}</select></label><label>Fecha objetivo<input type="date" name="due_date"></label><label class="full">Indicaciones<textarea name="note" rows="4" placeholder="Qué debe hacer la persona que recibe esta derivación"></textarea></label><div class="form-actions"><button type="button" class="secondary-btn" onclick="closeDetail()">Cancelar</button><button class="primary-btn">Derivar</button></div></form>`);const typeEl=$('jf83DeriveType'),ent=$('jf83DeriveEntity');const fill=()=>{const t=typeEl.value,list=t==='case'?cases:t==='message'?messages:t==='document'?documents:tasks;ent.innerHTML=list.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${esc(entityTitle(t,x.id))}</option>`).join('')};fill();typeEl.onchange=fill;$('jf83DeriveForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const{error}=await db.rpc('derive_workflow',{p_entity_type:f.get('entity_type'),p_entity_id:f.get('entity_id'),p_to_user:f.get('to_user'),p_note:f.get('note')||'',p_due_date:f.get('due_date')||null});if(error)return toast(error.message);closeModal();toast('Gestión derivada');await refresh('workflow83')}
  }
  async function replyDerivation(id,status){const note=(status==='Devuelta'||status==='Finalizada')?prompt('Observación / resultado (opcional):','')||'':'';const{error}=await db.rpc('respond_derivation',{p_derivation_id:id,p_status:status,p_note:note});if(error)return toast(error.message);toast('Derivación actualizada');await refresh('workflow83')}

  function changeCaseStage(id){const x=cases.find(v=>v.id===id);if(!x)return;modal('Cambiar etapa del trámite',`<form id="jf83StageForm" class="stack"><p><strong>${esc(x.case_number)} · ${esc(x.title)}</strong></p><label>Nueva etapa<select name="stage">${['Recepción','Análisis','Derivado','Esperando respuesta','En elaboración','Para aprobación','Aprobado','Resuelto','Cerrado'].map(s=>`<option ${s===x.workflow_stage?'selected':''}>${s}</option>`).join('')}</select></label><label>Motivo / avance<textarea name="note" rows="4"></textarea></label><div class="actions"><button class="primary-btn">Guardar etapa</button></div></form>`);$('jf83StageForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const{error}=await db.rpc('transition_case',{p_case_id:id,p_stage:f.get('stage'),p_note:f.get('note')||''});if(error)return toast(error.message);closeModal();toast('Etapa actualizada');await refresh('workflow83')}
  }

  function renderApprovals(){
    const mine=approvals.filter(x=>x.requested_to===profile.id&&x.status==='Pendiente'),pending=approvals.filter(x=>x.status==='Pendiente').length,signed=documents.filter(x=>x.workflow_status==='Firmado').length;$('jf83ApprovalStats').innerHTML=`<div class="stat"><span>Pendientes totales</span><strong>${pending}</strong></div><div class="stat"><span>Para mí</span><strong>${mine.length}</strong></div><div class="stat"><span>Aprobados</span><strong>${documents.filter(x=>x.workflow_status==='Aprobado').length}</strong></div><div class="stat"><span>Visto bueno / firma</span><strong>${signed}</strong></div>`;
    $('jf83MyApprovals').innerHTML=mine.length?mine.map(x=>{const d=documents.find(v=>v.id===x.document_id);const positive=x.stage==='Firma'?'Firmar internamente':'Aprobar';return `<div class="jf83-mini"><div><strong>${esc(d?.title||'Documento')}</strong><div class="meta">${esc(x.stage)} · solicitado por ${esc(x.requested_by_name)}</div>${x.request_comment?`<p>${esc(x.request_comment)}</p>`:''}</div>${canWrite()?`<div class="jf83-actions"><button class="primary-btn" onclick="JF83.decideApproval('${x.id}','${x.stage==='Firma'?'Firmado':'Aprobado'}')">${positive}</button><button onclick="JF83.decideApproval('${x.id}','Observado')">Observar</button><button onclick="JF83.decideApproval('${x.id}','Rechazado')">Rechazar</button></div>`:''}</div>`}).join(''):'<div class="empty">No tenés documentos pendientes de decisión.</div>';
    $('jf83Documents').innerHTML=documents.length?documents.slice(0,40).map(d=>`<div class="jf83-mini"><div><strong>${esc(d.title)}</strong><div class="meta">${esc(d.document_type)} · <span class="jf83-stage ${stageClass(d.workflow_status)}">${esc(d.workflow_status||'Borrador')}</span></div>${d.current_reviewer_name?`<small>En revisión por ${esc(d.current_reviewer_name)}</small>`:''}${d.approved_by_name?`<small>Aprobado por ${esc(d.approved_by_name)} · ${fmtDateTime(d.approved_at)}</small>`:''}${d.signed_by_name?`<small>Visto bueno de ${esc(d.signed_by_name)} · ${fmtDateTime(d.signed_at)}</small>`:''}</div>${canWrite()?`<button class="secondary-btn" onclick="JF83.requestApproval('${d.id}')">Solicitar acción</button>`:''}</div>`).join(''):'<div class="empty">Todavía no hay documentos generados.</div>'
  }
  function openApprovalForm(docId=''){if(!canWrite())return;modal('Solicitar acción sobre documento',`<form id="jf83ApprovalForm" class="form-grid"><label class="full">Documento<select name="document_id">${documents.map(d=>`<option value="${d.id}" ${d.id===docId?'selected':''}>${esc(d.title)} · ${esc(d.workflow_status||'Borrador')}</option>`).join('')}</select></label><label>Etapa<select name="stage"><option>Revisión</option><option>Aprobación</option><option>Firma</option></select></label><label>Asignar a<select name="to_user">${staffOptions()}</select></label><label class="full">Comentario<textarea name="comment" rows="4"></textarea></label><div class="form-actions"><button class="primary-btn">Enviar solicitud</button></div></form>`);$('jf83ApprovalForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const{error}=await db.rpc('request_document_approval',{p_document_id:f.get('document_id'),p_to_user:f.get('to_user'),p_stage:f.get('stage'),p_comment:f.get('comment')||''});if(error)return toast(error.message);closeModal();toast('Solicitud enviada');await refresh('approvals83')}}
  async function decideApproval(id,decision){const comment=decision==='Aprobado'||decision==='Firmado'?(prompt('Comentario opcional:','')||''):(prompt('Indicá la observación o motivo:','')||'');const{error}=await db.rpc('decide_document_approval',{p_approval_id:id,p_decision:decision,p_comment:comment});if(error)return toast(error.message);toast('Decisión registrada');await refresh('approvals83')}

  function renderMyWork(){
    const uid=profile.id,myAssignments=assignments.filter(x=>x.user_id===uid&&!['Completada','Rechazada'].includes(x.status)),myDer=derivations.filter(x=>x.to_user===uid&&openStatuses.has(x.status)),myApp=approvals.filter(x=>x.requested_to===uid&&x.status==='Pendiente'),myCases=cases.filter(x=>x.assigned_to===uid&&!['Cerrado','Resuelto'].includes(x.workflow_stage)),myMsg=messages.filter(x=>x.assigned_to===uid&&!['Respondida','Finalizada'].includes(x.status)),myAgenda=agenda.filter(x=>x.responsible_id===uid||(x.participant_ids||[]).includes(uid)).filter(x=>x.item_date>=today());$('jf83MyStats').innerHTML=`<div class="stat"><span>Asignaciones</span><strong>${myAssignments.length}</strong></div><div class="stat"><span>Derivaciones</span><strong>${myDer.length}</strong></div><div class="stat"><span>Aprobaciones</span><strong>${myApp.length}</strong></div><div class="stat"><span>Trámites</span><strong>${myCases.length}</strong></div><div class="stat"><span>Comunicaciones</span><strong>${myMsg.length}</strong></div><div class="stat"><span>Agenda próxima</span><strong>${myAgenda.length}</strong></div>`;
    const items=[];myApp.forEach(x=>items.push({rank:1,title:`${x.stage}: ${documents.find(d=>d.id===x.document_id)?.title||'Documento'}`,meta:'Aprobación pendiente'}));myDer.forEach(x=>items.push({rank:2,title:`Derivación · ${entityTitle(x.entity_type,x.entity_id)}`,meta:x.due_date?`Objetivo ${fmtDate(x.due_date)}`:x.status}));myCases.forEach(x=>items.push({rank:3,title:`${x.case_number} · ${x.title}`,meta:`${x.workflow_stage}${x.due_date?' · '+fmtDate(x.due_date):''}`}));myAssignments.forEach(x=>items.push({rank:4,title:tasks.find(t=>t.id===x.task_id)?.title||'Tarea asignada',meta:`${x.assignment_role} · ${x.status}`}));$('jf83MyPriority').innerHTML=items.length?items.sort((a,b)=>a.rank-b.rank).slice(0,20).map(x=>`<div class="jf83-mini"><strong>${esc(x.title)}</strong><div class="meta">${esc(x.meta)}</div></div>`).join(''):'<div class="empty">No hay acciones asignadas actualmente.</div>';
    const load=profiles.filter(p=>['admin','equipo'].includes(p.role)).map(p=>{const n=assignments.filter(x=>x.user_id===p.id&&!['Completada','Rechazada'].includes(x.status)).length+derivations.filter(x=>x.to_user===p.id&&openStatuses.has(x.status)).length+approvals.filter(x=>x.requested_to===p.id&&x.status==='Pendiente').length+cases.filter(x=>x.assigned_to===p.id&&!['Cerrado','Resuelto'].includes(x.workflow_stage)).length;return{p,n}}).sort((a,b)=>b.n-a.n);$('jf83TeamLoad').innerHTML=load.map(x=>`<div class="jf83-load"><span>${esc(x.p.full_name)}</span><strong>${x.n}</strong></div>`).join('')||'<div class="empty">Sin datos de carga.</div>';
    const timeline=[...myAgenda.map(x=>({date:x.item_date,title:x.title,meta:`Agenda · ${x.start_time?String(x.start_time).slice(0,5):''} ${x.location||''}`})),...tasks.filter(t=>myAssignments.some(a=>a.task_id===t.id)).map(t=>({date:t.deadline||t.task_date||'9999-12-31',title:t.title,meta:`Tarea · ${t.priority} · ${t.status}`}))].sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(0,30);$('jf83MyTimeline').innerHTML=timeline.length?timeline.map(x=>`<div class="jf83-row"><div><strong>${esc(x.title)}</strong><div class="meta">${x.date==='9999-12-31'?'Sin fecha':fmtDate(x.date)} · ${esc(x.meta)}</div></div></div>`).join(''):'<div class="empty">No hay agenda o tareas vinculadas.</div>'
  }

  function fillAuditFilters(){const el=$('jf83AuditActor');if(!el)return;const old=el.value;el.innerHTML='<option value="">Todas las personas</option>'+profiles.map(p=>`<option value="${p.id}">${esc(p.full_name)}</option>`).join('');el.value=old}
  function renderAudit(){const box=$('jf83AuditList');if(!box)return;const actor=$('jf83AuditActor')?.value||'',type=$('jf83AuditType')?.value||'',q=($('jf83AuditSearch')?.value||'').toLowerCase();let rows=audits.filter(x=>(!actor||x.actor_id===actor)&&(!type||x.entity_type===type)&&(!q||[x.actor_name,x.action,x.from_state,x.to_state,x.detail,x.entity_type].join(' ').toLowerCase().includes(q)));box.innerHTML=rows.length?rows.map(x=>`<div class="jf83-audit-row"><div class="jf83-audit-dot"></div><div><strong>${esc(x.actor_name||'Sistema')} · ${esc(x.action)}</strong><div class="meta">${fmtDateTime(x.created_at)} · ${esc(x.entity_type)}</div>${x.from_state||x.to_state?`<div class="jf83-transition">${esc(x.from_state||'—')} → <strong>${esc(x.to_state||'—')}</strong></div>`:''}${x.detail?`<p>${esc(x.detail)}</p>`:''}</div></div>`).join(''):'<div class="empty">No hay movimientos para este filtro.</div>'}
  async function entityHistory(type,id){await loadAudit();const aliases={case:['case','institutional_cases'],message:['message','institutional_messages'],document:['document','generated_documents'],task:['task','tasks','task_assignments']}[type]||[type];const rows=audits.filter(x=>x.entity_id===id&&aliases.includes(x.entity_type));modal('Historial · '+entityTitle(type,id),rows.length?`<div class="jf83-audit">${rows.map(x=>`<div class="jf83-audit-row"><div class="jf83-audit-dot"></div><div><strong>${esc(x.actor_name||'Sistema')} · ${esc(x.action)}</strong><div class="meta">${fmtDateTime(x.created_at)}</div>${x.from_state||x.to_state?`<div>${esc(x.from_state||'—')} → <strong>${esc(x.to_state||'—')}</strong></div>`:''}${x.detail?`<p>${esc(x.detail)}</p>`:''}</div></div>`).join('')}</div>`:'<div class="empty">Todavía no hay movimientos registrados.</div>')}

  window.JF83={derive:(type,id)=>openDerivationForm(type,id),replyDerivation,changeCaseStage,requestApproval:openApprovalForm,decideApproval,entityHistory};
  function scan(){auth().then(()=>{if(profile?.active){inject();const hash=(location.hash||'').replace('#/','');if(['workflow83','approvals83','mywork83','audit83'].includes(hash))refresh(hash).catch(console.error)}})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan,{once:true});else scan();window.addEventListener('hashchange',()=>setTimeout(scan,120));setInterval(()=>{if(profile?.active)inject()},1800);
})();