(function installTeamUIV4(){
  if(window.__JF_TEAM_UI_V4__)return;window.__JF_TEAM_UI_V4__=true;
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const REC='jf_team_recent_views_v4',COL='jf_team_sidebar_collapsed_v4';let palette=null,navObserver=null,mainObserver=null;
  const H={dashboard:'Inicio y prioridades del día',tasks:'Pendientes y seguimientos',calendar:'Agenda general',events:'Actividades y eventos',meetings:'Coordinaciones y reuniones',projects:'Proyectos de la Oficina',contacts:'Personas de contacto',institutions:'Red institucional',notes:'Notas y solicitudes',participation:'Alcance y participación',opportunities:'Becas, cursos y oportunidades',checkin:'Asistencia mediante QR',reports:'Informes y exportaciones',settings:'Usuarios e integraciones',operations81:'Centro operativo',inbox82:'Entrada y salida institucional',cases82:'Expedientes y solicitudes',teamagenda82:'Agenda compartida',assignments82:'Responsabilidades del equipo',workflow83:'Trámites y derivaciones',approvals83:'Revisión y visto bueno',mywork83:'Trabajo personal',audit83:'Trazabilidad institucional',documents84:'Documentos oficiales',documentbook84:'Libro y archivo',management85:'Indicadores de gestión',goals85:'Metas institucionales',monthlyreport85:'Informe mensual',poa86:'Plan Operativo Anual',assistant:'Asistente Juventud'};
  const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const appVisible=()=>!$('#app')?.classList.contains('hidden');
  const nav=()=>$('#mainNav'),buttons=()=>$$('#mainNav button[data-view]');
  function rawLabel(b){return b?.dataset.jfTeamLabel||b?.textContent?.trim()||''}
  function parts(s){const m=String(s).trim().match(/^(\S+)\s+(.+)$/);return m?{icon:m[1],text:m[2]}:{icon:'•',text:s}}
  function decorate(b){if(!b||b.dataset.jfTeamV4==='1')return;b.dataset.jfTeamV4='1';b.dataset.jfTeamLabel=b.textContent.trim();const p=parts(b.dataset.jfTeamLabel);b.innerHTML=`<span class="jf-team-nav-icon" aria-hidden="true">${esc(p.icon)}</span><span class="jf-team-nav-text">${esc(p.text)}</span>`;b.title=p.text;b.setAttribute('aria-label',p.text)}
  function label(view){const b=buttons().find(x=>x.dataset.view===view);return b?parts(rawLabel(b)).text:view}
  function loadJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}}
  function record(view){if(!view)return;const r=loadJSON(REC,[]).filter(x=>x!==view);r.unshift(view);localStorage.setItem(REC,JSON.stringify(r.slice(0,5)));renderRecents();syncContext()}
  function ensureSidebar(){const side=$('#sidebar'),brand=side?.querySelector('.brand');if(!side||!brand)return;if(!$('#jfTeamSidebarTop')){const t=document.createElement('div');t.id='jfTeamSidebarTop';t.className='jf-team-sidebar-top';t.innerHTML='<button id="jfTeamCollapse" class="jf-team-collapse" type="button" aria-label="Contraer menú"><span>⇤</span></button><button id="jfTeamNavSearchBtn" class="jf-team-nav-search" type="button"><span>⌕</span><span class="jf-team-nav-search-copy">Buscar módulo</span><kbd>⌘K</kbd></button>';brand.insertAdjacentElement('afterend',t);$('#jfTeamCollapse').onclick=toggleCollapse;$('#jfTeamNavSearchBtn').onclick=()=>openPalette('')}
    if(!$('#jfTeamRecents')){const r=document.createElement('div');r.id='jfTeamRecents';r.className='jf-team-recents';nav()?.insertAdjacentElement('beforebegin',r)}applyCollapse();renderRecents()}
  function toggleCollapse(){if(matchMedia('(max-width:980px)').matches)return;const n=!document.body.classList.contains('jf-team-sidebar-collapsed');document.body.classList.toggle('jf-team-sidebar-collapsed',n);localStorage.setItem(COL,n?'1':'0')}
  function applyCollapse(){if(matchMedia('(max-width:980px)').matches){document.body.classList.remove('jf-team-sidebar-collapsed');return}document.body.classList.toggle('jf-team-sidebar-collapsed',localStorage.getItem(COL)==='1')}
  function renderRecents(){const box=$('#jfTeamRecents');if(!box)return;const rows=loadJSON(REC,[]).filter(v=>buttons().some(b=>b.dataset.view===v)).slice(0,4);if(!rows.length){box.innerHTML='';box.classList.add('hidden');return}box.classList.remove('hidden');box.innerHTML=`<div class="jf-team-recent-label">Recientes</div><div class="jf-team-recent-list">${rows.map(v=>{const b=buttons().find(x=>x.dataset.view===v),p=parts(rawLabel(b));return`<button type="button" data-recent="${esc(v)}"><span>${esc(p.icon)}</span><span>${esc(p.text)}</span></button>`}).join('')}</div>`;box.querySelectorAll('[data-recent]').forEach(b=>b.onclick=()=>buttons().find(x=>x.dataset.view===b.dataset.recent)?.click())}
  function ensureContext(){const top=$('.topbar');if(!top)return;if(!$('#jfTeamContext')){const c=document.createElement('div');c.id='jfTeamContext';c.className='jf-team-context';c.innerHTML='<span class="jf-team-context-kicker">JUVENTUD FLORES</span><strong id="jfTeamContextTitle">Mi día</strong>';top.insertBefore(c,top.querySelector('.search')||top.firstChild)}const search=top.querySelector('.search'),input=search?.querySelector('input');if(search&&!search.dataset.jfTeamV4){search.dataset.jfTeamV4='1';search.classList.add('jf-team-command-search');if(input){input.placeholder='Buscar módulo, acción o contenido…';input.addEventListener('focus',()=>openPalette(input.value));input.addEventListener('input',()=>{if(appVisible())openPalette(input.value,{keepFocus:true})})}const k=document.createElement('kbd');k.className='jf-team-search-kbd';k.textContent='⌘K';search.appendChild(k)}}
  function activeView(){return buttons().find(b=>b.classList.contains('active'))?.dataset.view||'dashboard'}
  function syncContext(){const n=$('#jfTeamContextTitle');if(n)n.textContent=label(activeView())||'Juventud Flores';document.body.dataset.jfTeamView=activeView()}
  function improveHeads(){$$('.main>.view .page-head').forEach(h=>{if(h.dataset.jfTeamV4)return;h.dataset.jfTeamV4='1';const d=h.querySelector(':scope > div'),title=d?.querySelector('h1'),view=h.closest('.view')?.id?.replace('view-',''),hint=H[view];if(title&&hint&&!d.querySelector('.jf-team-page-subtitle')){const p=document.createElement('p');p.className='jf-team-page-subtitle';p.textContent=hint;title.insertAdjacentElement('afterend',p)}})}
  function ensureScrim(){if($('#jfTeamSidebarScrim'))return;const s=document.createElement('div');s.id='jfTeamSidebarScrim';s.className='jf-team-sidebar-scrim';s.onclick=()=>$('#sidebar')?.classList.remove('open');document.body.appendChild(s)}
  function syncScrim(){const s=$('#jfTeamSidebarScrim'),side=$('#sidebar');if(s&&side)s.classList.toggle('show',matchMedia('(max-width:980px)').matches&&side.classList.contains('open')&&appVisible())}
  function commands(){const mods=buttons().map(b=>{const p=parts(rawLabel(b));return{kind:'module',id:b.dataset.view,icon:p.icon,title:p.text,sub:H[b.dataset.view]||'Abrir módulo'}});return[{kind:'action',id:'new-task',icon:'✅',title:'Nueva tarea rápida',sub:'Crear desde una frase'},{kind:'action',id:'new-reminder',icon:'⏰',title:'Nuevo recordatorio',sub:'Crear aviso rápido'},{kind:'action',id:'new-meeting',icon:'🤝',title:'Nueva reunión',sub:'Crear desde una frase'},{kind:'action',id:'new-event',icon:'🎪',title:'Nuevo evento',sub:'Crear desde una frase'},{kind:'action',id:'quick-add',icon:'＋',title:'Agregar otro registro',sub:'Abrir carga ultrarrápida'},...mods]}
  function buildPalette(){if(palette)return;palette=document.createElement('div');palette.id='jfTeamPalette';palette.className='jf-team-palette';palette.innerHTML='<div class="jf-team-palette-backdrop" data-close></div><section class="jf-team-palette-panel" role="dialog" aria-modal="true"><div class="jf-team-palette-input"><span>⌕</span><input id="jfTeamPaletteInput" placeholder="Escribí: tareas, expediente, reunión…"><kbd>ESC</kbd></div><div id="jfTeamPaletteResults" class="jf-team-palette-results"></div><footer><span>↑↓ navegar</span><span>Enter abrir</span><span>⌘K buscar</span></footer></section>';document.body.appendChild(palette);palette.querySelector('[data-close]').onclick=closePalette;$('#jfTeamPaletteInput').addEventListener('input',e=>renderPalette(e.target.value));$('#jfTeamPaletteInput').addEventListener('keydown',paletteKeys)}
  function renderPalette(q=''){const n=String(q).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(),rows=commands().filter(x=>!n||`${x.title} ${x.sub}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(n)).slice(0,14),box=$('#jfTeamPaletteResults');if(!box)return;box.innerHTML=rows.length?rows.map((x,i)=>`<button type="button" class="jf-team-command ${i===0?'selected':''}" data-kind="${x.kind}" data-id="${esc(x.id)}"><span class="jf-team-command-icon">${esc(x.icon)}</span><span><strong>${esc(x.title)}</strong><small>${esc(x.sub)}</small></span><span class="jf-team-command-enter">↵</span></button>`).join(''):'<div class="jf-team-command-empty">No encontré esa opción.</div>';box.querySelectorAll('.jf-team-command').forEach(b=>b.onclick=()=>run(b))}
  function openPalette(q='',o={}){if(!appVisible())return;buildPalette();palette.classList.add('open');const i=$('#jfTeamPaletteInput');i.value=q||'';renderPalette(i.value);if(!o.keepFocus)setTimeout(()=>i.focus(),0)}
  function closePalette(){palette?.classList.remove('open')}
  function run(b){const kind=b.dataset.kind,id=b.dataset.id;closePalette();if(kind==='module')return buttons().find(x=>x.dataset.view===id)?.click();if(id==='new-task')return window.JFQuickTask?.open?.('task');if(id==='new-reminder')return window.JFQuickTask?.open?.('reminder');if(id==='new-meeting')return window.JFQuickSchedule?.open?.('meeting');if(id==='new-event')return window.JFQuickSchedule?.open?.('event');$('#quickAddBtn')?.click()}
  function paletteKeys(e){const rows=$$('#jfTeamPaletteResults .jf-team-command');if(!rows.length)return;let i=Math.max(0,rows.findIndex(x=>x.classList.contains('selected')));if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();rows[i].classList.remove('selected');i=e.key==='ArrowDown'?(i+1)%rows.length:(i-1+rows.length)%rows.length;rows[i].classList.add('selected');rows[i].scrollIntoView({block:'nearest'})}else if(e.key==='Enter'){e.preventDefault();run(rows[i])}else if(e.key==='Escape'){closePalette()}}
  function sync(){if(!appVisible())return;document.body.classList.add('jf-team-ui-v3');buttons().forEach(decorate);ensureSidebar();ensureContext();ensureScrim();improveHeads();syncContext();syncScrim()}
  function observe(){if(nav()&&!navObserver){navObserver=new MutationObserver(()=>requestAnimationFrame(sync));navObserver.observe(nav(),{childList:true})}const main=$('.main');if(main&&!mainObserver){mainObserver=new MutationObserver(()=>requestAnimationFrame(()=>{improveHeads();syncContext()}));mainObserver.observe(main,{childList:true})}}
  nav()?.addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(!b)return;record(b.dataset.view);requestAnimationFrame(()=>{syncContext();syncScrim()})});
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette('')}else if(e.key==='Escape')closePalette()});
  window.addEventListener('resize',()=>{applyCollapse();syncScrim()},{passive:true});
  window.addEventListener('jf:state-updated',()=>{if(appVisible())requestAnimationFrame(syncContext)});
  sync();observe();setTimeout(()=>{sync();observe()},600);setTimeout(()=>{sync();observe()},1600);
})();