(function installSorayaUniversalSearch(){
  if(window.__SORAYA_UNIVERSAL_SEARCH__)return;window.__SORAYA_UNIVERSAL_SEARCH__=true;
  const C=window.JF_CONFIG;if(!C||!window.supabase)return;
  const db=window.JF_DB||window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const rank={Urgente:1,Alta:2,Media:3,Baja:4};
  const TYPES={
    tasks:{label:'Tareas',icon:'✅',view:'tasks'},notes:{label:'Notas y solicitudes',icon:'📄',view:'notes'},meetings:{label:'Reuniones',icon:'🤝',view:'meetings'},events:{label:'Eventos',icon:'🎪',view:'events'},projects:{label:'Proyectos',icon:'📂',view:'projects'},messages:{label:'Comunicaciones',icon:'📥',view:'inbox82'},cases:{label:'Expedientes',icon:'🗂️',view:'cases82'},documents:{label:'Documentos oficiales',icon:'📑',view:'officialdocs84'},opportunities:{label:'Oportunidades',icon:'🎓',view:'opportunities'}
  };
  let modal=null,cache=[],profiles=[],loadedAt=0,loading=false,timer=null,currentType='';
  const ttl=120000;
  function fmt(v){if(!v)return'';try{return new Intl.DateTimeFormat('es-UY',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(String(v).slice(0,10)+'T12:00:00'))}catch{return String(v)}}
  function appVisible(){return !$('#app')?.classList.contains('hidden')}
  function mapRows(key,rows){return (rows||[]).map(x=>{
    let title='',summary='',status='',priority='',date='',responsibleId='',responsibleName='',search='';
    if(key==='tasks'){title=x.title;summary=[x.description,x.category,x.institution_name,x.project_name].filter(Boolean).join(' · ');status=x.status;priority=x.priority;date=x.deadline||x.task_date;responsibleId=x.responsible_id||'';}
    if(key==='notes'){title=x.subject;summary=[x.number,x.recipient,x.department,x.reason].filter(Boolean).join(' · ');status=x.status;date=x.note_date;responsibleName=x.responsible_name||'';}
    if(key==='meetings'){title=x.subject;summary=[x.place,x.institutions,x.participants,x.discussed,x.decisions,x.commitments].filter(Boolean).join(' · ');date=x.meeting_date;}
    if(key==='events'){title=x.name;summary=[x.place,x.organizer,x.collaborators,x.target_audience,x.description].filter(Boolean).join(' · ');date=x.event_date;responsibleName=x.responsible_name||'';}
    if(key==='projects'){title=x.name;summary=[x.objective,x.description,x.results].filter(Boolean).join(' · ');status=x.status;date=x.start_date||x.end_date;}
    if(key==='messages'){title=x.subject;summary=[x.direction,x.channel,x.sender,x.recipient,x.institution_name,x.summary].filter(Boolean).join(' · ');status=x.status;priority=x.priority;date=x.registered_date;responsibleId=x.assigned_to||'';responsibleName=x.assigned_name||'';}
    if(key==='cases'){title=(x.case_number?x.case_number+' · ':'')+x.title;summary=[x.case_type,x.institution_name,x.description,x.resolution].filter(Boolean).join(' · ');status=x.status;priority=x.priority;date=x.due_date||x.opened_date;responsibleId=x.assigned_to||'';responsibleName=x.assigned_name||'';}
    if(key==='documents'){title=(x.official_number?x.official_number+' · ':'')+x.title;summary=[x.document_type,x.recipient,x.department].filter(Boolean).join(' · ');status=x.official_status;date=x.issue_date;}
    if(key==='opportunities'){title=x.title;summary=[x.category,x.organization,x.summary,x.locality].filter(Boolean).join(' · ');status=x.status;date=x.deadline;}
    if(!responsibleName&&responsibleId)responsibleName=profiles.find(p=>p.id===responsibleId)?.full_name||'';
    search=norm([title,summary,status,priority,responsibleName].join(' '));
    return{key,id:x.id,title:title||'Sin título',summary,status,priority,date,responsibleId,responsibleName,raw:x,search,updated:x.updated_at||x.created_at||date||''};
  })}
  async function load(force=false){
    if(loading)return;if(!force&&cache.length&&Date.now()-loadedAt<ttl)return;loading=true;renderLoading();
    try{
      const {data:{session}}=await db.auth.getSession();if(!session?.user)return;
      const calls=[
        db.from('profiles').select('id,full_name,role,active').eq('active',true).order('full_name'),
        db.from('tasks').select('id,title,description,category,status,priority,task_date,deadline,responsible_id,institution_name,project_name,updated_at').eq('archived',false).limit(700),
        db.from('notes').select('id,note_date,number,recipient,department,subject,reason,status,followup_date,responsible_name,updated_at').eq('archived',false).limit(600),
        db.from('meetings').select('id,subject,meeting_date,meeting_time,place,institutions,participants,discussed,decisions,commitments,next_steps,updated_at').eq('archived',false).limit(500),
        db.from('events').select('id,name,event_date,start_time,place,organizer,collaborators,target_audience,description,responsible_name,updated_at').eq('archived',false).limit(500),
        db.from('projects').select('id,name,status,start_date,end_date,objective,description,results,updated_at').eq('archived',false).limit(400),
        db.from('institutional_messages').select('id,direction,registered_date,registered_time,channel,sender,recipient,institution_name,subject,summary,status,priority,assigned_to,assigned_name,response_due_date,updated_at').eq('archived',false).limit(600),
        db.from('institutional_cases').select('id,case_number,title,case_type,institution_name,status,priority,opened_date,due_date,assigned_to,assigned_name,description,resolution,updated_at').eq('archived',false).limit(600),
        db.from('generated_documents').select('id,official_number,document_type,title,recipient,department,official_status,issue_date,created_at').eq('archived',false).limit(600),
        db.from('opportunities').select('id,title,category,organization,status,summary,locality,deadline,updated_at').eq('archived',false).limit(400)
      ];
      const res=await Promise.all(calls);profiles=res[0].data||[];const keys=['tasks','notes','meetings','events','projects','messages','cases','documents','opportunities'];cache=[];keys.forEach((k,i)=>{if(res[i+1].error)console.warn('[Soraya búsqueda]',k,res[i+1].error);else cache.push(...mapRows(k,res[i+1].data))});loadedAt=Date.now();fillDynamicFilters();render();
    }catch(e){console.warn('[Soraya búsqueda]',e);renderError()}finally{loading=false}
  }
  function build(){if(modal)return modal;modal=document.createElement('div');modal.id='sorayaUniversalSearch';modal.className='soraya-search-overlay';modal.innerHTML=`<div class="soraya-search-backdrop" data-search-close></div><section class="soraya-search-panel" role="dialog" aria-modal="true" aria-label="Buscar en Soraya"><header class="soraya-search-head"><span>🔎</span><input id="sorayaSearchInput" class="main-input" placeholder="Buscar tarea, nota, reunión, evento, expediente…" autocomplete="off"><button type="button" data-search-close aria-label="Cerrar">×</button></header><div class="soraya-search-body"><aside class="soraya-search-filters"><label>Tipo<select id="sorayaSearchType"><option value="">Todos</option>${Object.entries(TYPES).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('')}</select></label><label>Estado<select id="sorayaSearchStatus"><option value="">Todos</option></select></label><label>Prioridad<select id="sorayaSearchPriority"><option value="">Todas</option><option>Urgente</option><option>Alta</option><option>Media</option><option>Baja</option></select></label><label>Responsable<select id="sorayaSearchResponsible"><option value="">Todos</option></select></label><label>Desde<input id="sorayaSearchFrom" type="date"></label><label>Hasta<input id="sorayaSearchTo" type="date"></label><div class="soraya-search-filter-actions"><button type="button" id="sorayaSearchClear">Limpiar filtros</button><button type="button" id="sorayaSearchRefresh">Actualizar</button></div></aside><main class="soraya-search-results-wrap"><div class="soraya-search-summary"><strong id="sorayaSearchCount">Buscar en Soraya</strong><span>Enter abre el primer resultado</span></div><div id="sorayaSearchResults" class="soraya-search-results"></div></main></div></section>`;document.body.appendChild(modal);modal.querySelectorAll('[data-search-close]').forEach(b=>b.onclick=close);$('#sorayaSearchInput').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(render,100)});['#sorayaSearchType','#sorayaSearchStatus','#sorayaSearchPriority','#sorayaSearchResponsible','#sorayaSearchFrom','#sorayaSearchTo'].forEach(s=>$(s).addEventListener('change',render));$('#sorayaSearchClear').onclick=clearFilters;$('#sorayaSearchRefresh').onclick=()=>load(true);$('#sorayaSearchInput').addEventListener('keydown',e=>{if(e.key==='Enter'){const b=$('.soraya-result');if(b){e.preventDefault();b.click()}}});return modal}
  function fillDynamicFilters(){if(!modal)return;const st=$('#sorayaSearchStatus'),rs=$('#sorayaSearchResponsible');const oldS=st.value,oldR=rs.value;const states=[...new Set(cache.map(x=>x.status).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));st.innerHTML='<option value="">Todos</option>'+states.map(x=>`<option>${esc(x)}</option>`).join('');st.value=states.includes(oldS)?oldS:'';const people=[...new Set([...profiles.map(p=>p.full_name),...cache.map(x=>x.responsibleName)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));rs.innerHTML='<option value="">Todos</option>'+people.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');rs.value=people.includes(oldR)?oldR:''}
  function filtered(){const q=norm($('#sorayaSearchInput')?.value||''),type=$('#sorayaSearchType')?.value||'',st=$('#sorayaSearchStatus')?.value||'',pr=$('#sorayaSearchPriority')?.value||'',resp=$('#sorayaSearchResponsible')?.value||'',from=$('#sorayaSearchFrom')?.value||'',to=$('#sorayaSearchTo')?.value||'';let rows=cache.filter(x=>(!q||x.search.includes(q))&&(!type||x.key===type)&&(!st||x.status===st)&&(!pr||x.priority===pr)&&(!resp||x.responsibleName===resp)&&(!from||x.date&&x.date>=from)&&(!to||x.date&&x.date<=to));rows.sort((a,b)=>{if(q){const aq=norm(a.title),bq=norm(b.title);const as=aq.startsWith(q)?0:aq.includes(q)?1:2,bs=bq.startsWith(q)?0:bq.includes(q)?1:2;if(as!==bs)return as-bs}const ap=rank[a.priority]||9,bp=rank[b.priority]||9;if(ap!==bp)return ap-bp;return String(b.updated||'').localeCompare(String(a.updated||''))});return rows.slice(0,160)}
  function render(){if(!modal)return;const box=$('#sorayaSearchResults');if(!box)return;const rows=filtered();$('#sorayaSearchCount').textContent=`${rows.length}${rows.length===160?'+':''} resultado${rows.length===1?'':'s'}`;box.innerHTML=rows.length?rows.map(x=>{const t=TYPES[x.key];return`<button type="button" class="soraya-result" data-search-key="${x.key}" data-search-id="${esc(x.id)}"><span class="soraya-result-icon">${t.icon}</span><span><h3>${esc(x.title)}</h3><p>${esc([t.label,x.summary].filter(Boolean).join(' · '))}</p></span><span class="soraya-result-tags">${x.status?`<span class="soraya-result-tag">${esc(x.status)}</span>`:''}${x.priority?`<span class="soraya-result-tag ${esc(x.priority)}">${esc(x.priority)}</span>`:''}${x.date?`<span class="soraya-result-tag">${fmt(x.date)}</span>`:''}${x.responsibleName?`<span class="soraya-result-tag">👤 ${esc(x.responsibleName)}</span>`:''}</span></button>`}).join(''):'<div class="soraya-search-empty"><strong>No encontramos resultados</strong><p>Probá con menos palabras o quitá algún filtro.</p></div>';box.querySelectorAll('.soraya-result').forEach(b=>b.onclick=()=>openResult(b.dataset.searchKey,b.dataset.searchId))}
  function renderLoading(){if(modal&&$('#sorayaSearchResults'))$('#sorayaSearchResults').innerHTML='<div class="soraya-search-loading">Buscando en Soraya…</div>'}
  function renderError(){if(modal&&$('#sorayaSearchResults'))$('#sorayaSearchResults').innerHTML='<div class="soraya-search-empty">No se pudo actualizar el buscador. Intentá nuevamente.</div>'}
  function clearFilters(){['#sorayaSearchStatus','#sorayaSearchPriority','#sorayaSearchResponsible','#sorayaSearchFrom','#sorayaSearchTo'].forEach(s=>{if($(s))$(s).value=''});$('#sorayaSearchType').value=currentType||'';render()}
  function open(type='',query=''){build();currentType=type||'';$('#sorayaSearchType').value=currentType;$('#sorayaSearchInput').value=query||'';modal.classList.add('open');setTimeout(()=>$('#sorayaSearchInput')?.focus(),30);load(false).then(render)}
  function close(){if(!modal)return;modal.classList.remove('open');currentType=''}
  function navigate(view,inputId,value){close();document.querySelector(`#mainNav [data-view="${view}"]`)?.click();setTimeout(()=>{const i=document.getElementById(inputId);if(i){i.value=value;i.dispatchEvent(new Event('input',{bubbles:true}));i.focus()}},500)}
  function openResult(key,id){const x=cache.find(r=>r.key===key&&String(r.id)===String(id));if(!x)return;if(['tasks','notes','meetings','events','projects','opportunities'].includes(key)&&typeof window.openDetails==='function'){close();window.openDetails(key,id);return}if(key==='messages'){navigate('inbox82','jf82MsgSearch',x.raw.subject||x.title);return}if(key==='cases'){navigate('cases82','jf82CaseSearch',x.raw.case_number||x.raw.title);return}if(key==='documents'){navigate('officialdocs84','jf84Search',x.raw.official_number||x.raw.title);return}}
  function moduleButtons(){const defs=[['#view-tasks','tasks'],['#view-notes','notes'],['#view-meetings','meetings'],['#view-events','events'],['#view-projects','projects'],['#view-opportunities','opportunities'],['#view-inbox82','messages'],['#view-cases82','cases'],['#view-officialdocs84','documents']];defs.forEach(([sel,type])=>{const head=$(sel+' .page-head');if(!head||head.querySelector('[data-soraya-search-type]'))return;const actions=head.querySelector('.actions');const b=document.createElement('button');b.type='button';b.className='secondary-btn soraya-module-search-btn';b.dataset.sorayaSearchType=type;b.textContent='🔎 Buscar y filtrar';b.onclick=()=>open(type,'');if(actions)actions.prepend(b);else head.appendChild(b)})}
  function installTop(){const input=$('#globalSearch');if(!input||input.dataset.sorayaGlobal)return;input.dataset.sorayaGlobal='1';input.placeholder='Buscar en Soraya…';input.setAttribute('readonly','readonly');input.addEventListener('click',()=>open('',input.value||''));input.addEventListener('focus',()=>open('',input.value||''));const wrap=input.closest('.search');if(wrap){wrap.style.cursor='pointer';wrap.addEventListener('click',e=>{if(e.target!==input)open('','')})}}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('open'))close();if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='f'){e.preventDefault();open('','')}});
  window.addEventListener('hashchange',()=>setTimeout(moduleButtons,250));window.addEventListener('jf:data-changed',()=>{loadedAt=0});document.addEventListener('jf:data-changed',()=>{loadedAt=0});
  installTop();moduleButtons();setTimeout(moduleButtons,1000);setTimeout(moduleButtons,2200);
  window.SorayaSearch={open,refresh:()=>load(true),invalidate:()=>{loadedAt=0}};
})();
